//! `ridge_solvers` — the host arms of `Ridge`'s sklearn solver set (LINEAR-02).
//!
//! `sklearn.linear_model.Ridge` exposes EIGHT `solver` values
//! (`auto`/`svd`/`cholesky`/`lsqr`/`sparse_cg`/`sag`/`saga`/`lbfgs`). Two of
//! them are direct factorizations that map onto validated device primitives and
//! therefore live in `ridge.rs` itself:
//!
//! - `cholesky` — the `(XᵀX + αI)·coef = Xᵀy` normal-equations solve on the
//!   `cholesky_solve` prim (the default `auto` resolution, unchanged);
//! - `svd` — `coef = V·diag(σ/(σ²+α))·Uᵀ·y` on the `svd` prim.
//!
//! The remaining FOUR are ITERATIVE, and this module owns them. They run on the
//! host in `f64` regardless of the estimator's `F`, for three reasons:
//!
//! 1. **They are `O(d)`/`O(d²)`-per-step scalar recurrences, not data-parallel
//!    kernels.** The heavy `O(n·d)` work (`XᵀX`, `Xᵀy`, the centering) is still
//!    done on-device by `gram_xty` / `center_columns`; `sparse_cg` and the
//!    `positive` arm consume ONLY those `d×d` / `d` reductions, so they never
//!    touch `X` at all. `lsqr` and `sag`/`saga` genuinely need per-row access
//!    (that is what distinguishes them from a normal-equations solve), so they
//!    read the centered design back once.
//! 2. **A per-iteration device round trip is the known pathology in this
//!    codebase**, not a hypothetical one — the same host-arm shape that fixed
//!    `sgd_solve`, HDBSCAN's core-distance scan, and UMAP's per-epoch layout.
//! 3. **`f64` accumulation makes the `f32` estimator MORE sklearn-faithful, not
//!    less.** The oracle fixtures are generated by sklearn in `f64` and only
//!    then cast, so an `f64` iteration reproduces the reference more closely
//!    than an `f32` one would.
//!
//! ## What "matches sklearn" means for an iterative solver
//! Ridge's objective `‖y − Xw‖² + α‖w‖²` is strictly convex for `α > 0`, so it
//! has ONE minimizer and every solver here converges to that same point. The
//! oracle contract is therefore agreement on the CONVERGED coefficients (within
//! the 1e-5 abs+rel gate when both sides are run to a tight `tol`), NOT
//! iteration-for-iteration equality with scipy's `cg`/`lsqr`/`sag` — those are
//! implementation details sklearn itself does not promise across scipy versions.
//! Where sklearn's own step-size / stopping constants are load-bearing for the
//! FIXED POINT rather than just the path (SAG's `get_auto_step_size`), they are
//! reproduced exactly and cited inline.
//!
//! Tests live in `crates/mlrs-algos/tests/ridge_params_test.rs` (AGENTS.md §2).

/// Deterministic splitmix64 stream — the seeded permutation source for
/// `sag`/`saga` (`random_state`). Counter-based, so it is reproducible and
/// stateless-restartable, matching the `bench_linear.py` / `*_perf_test.rs`
/// splitmix64 precedent already used across this workspace.
struct SplitMix64(u64);

impl SplitMix64 {
    fn new(seed: u64) -> Self {
        Self(seed)
    }

    fn next_u64(&mut self) -> u64 {
        self.0 = self.0.wrapping_add(0x9E37_79B9_7F4A_7C15);
        let mut z = self.0;
        z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
        z ^ (z >> 31)
    }

    /// Uniform index in `[0, n)`. `n` is the sample count (never 0 — the caller
    /// validated the geometry), so the modulo bias over a 64-bit draw is far
    /// below any effect on the converged fixed point.
    fn index(&mut self, n: usize) -> usize {
        (self.next_u64() % n as u64) as usize
    }
}

/// Conjugate gradients on the normal equations — the `solver='sparse_cg'` arm.
///
/// sklearn's `_solve_sparse_cg` builds a `LinearOperator` whose `matvec` is
/// `x ↦ Xᵀ(X·x) + α·x` and hands it, with the right-hand side `Xᵀy`, to
/// `scipy.sparse.linalg.cg(..., rtol=tol, maxiter=max_iter)` (the
/// `n_features <= n_samples` branch; the transposed branch is the kernel form
/// and yields the same `coef`). That operator IS `(G + αI)` with `G = XᵀX`, so
/// consuming the device-formed `gram`/`xty` is not an approximation of sklearn's
/// path — it is the same operator with the `matvec` precomputed once instead of
/// re-applied `O(n·d)` per iteration.
///
/// - `gram` is the row-major `d×d` raw Gram `XᵀX` (NOT `α`-shifted — `alpha` is
///   applied by the operator here, exactly as sklearn's `_mv` does).
/// - `xty` is the length-`d` `Xᵀy`.
/// - `tol` is scipy's RELATIVE residual tolerance (`‖r‖ ≤ tol·‖b‖`; scipy's
///   `atol` defaults to `0.0`).
/// - `max_iter` `None` takes scipy's `10·d` default.
///
/// Returns the coefficients. CG on a `d`-dimensional SPD system terminates in at
/// most `d` exact-arithmetic steps, so this is a direct solve in disguise for
/// the feature counts this estimator targets — which is precisely why sklearn
/// does not expose an `n_iter_` for `sparse_cg` (see `ridge.rs`'s `n_iter_`
/// note) and neither does this function.
pub fn sparse_cg(
    gram: &[f64],
    xty: &[f64],
    d: usize,
    alpha: f64,
    tol: f64,
    max_iter: Option<usize>,
) -> Vec<f64> {
    let max_iter = max_iter.unwrap_or(10 * d);
    let mut w = vec![0.0f64; d];

    // r = b − A·0 = b; p = r.
    let mut r = xty.to_vec();
    let mut p = r.clone();
    let mut rs = dot(&r, &r);
    let b_norm = dot(xty, xty).sqrt();
    if b_norm == 0.0 {
        return w;
    }
    let target = tol * b_norm;

    let mut ap = vec![0.0f64; d];
    for _ in 0..max_iter {
        if rs.sqrt() <= target {
            break;
        }
        // ap = (G + αI)·p — the sklearn `_mv` operator.
        for i in 0..d {
            let row = &gram[i * d..(i + 1) * d];
            ap[i] = dot(row, &p) + alpha * p[i];
        }
        let denom = dot(&p, &ap);
        if denom <= 0.0 || !denom.is_finite() {
            // A non-positive curvature can only come from a non-SPD operator
            // (α = 0 with a singular Gram). Stop with the best iterate rather
            // than dividing by ~0 and emitting NaN coefficients.
            break;
        }
        let step = rs / denom;
        for j in 0..d {
            w[j] += step * p[j];
            r[j] -= step * ap[j];
        }
        let rs_new = dot(&r, &r);
        let beta = rs_new / rs;
        for j in 0..d {
            p[j] = r[j] + beta * p[j];
        }
        rs = rs_new;
    }
    w
}

/// Paige–Saunders LSQR on the DAMPED least-squares system — the
/// `solver='lsqr'` arm.
///
/// sklearn's `_solve_lsqr` calls `scipy.sparse.linalg.lsqr(X, y,
/// damp=sqrt(alpha), atol=tol, btol=tol, iter_lim=max_iter)`. LSQR applies the
/// Golub–Kahan bidiagonalization to `X` DIRECTLY — it never forms `XᵀX` — which
/// is the whole point of the solver: it keeps the condition number of `X`
/// rather than squaring it. This is a faithful transcription of that recurrence
/// (including the `damp` plane rotation), so the ill-conditioned behaviour that
/// distinguishes `lsqr` from `cholesky` is preserved.
///
/// - `x` is the row-major `n×d` (already centered / sample-weight-rescaled)
///   design; `y` the matching length-`n` target.
/// - `alpha` is the ridge penalty; the LSQR damping is `sqrt(alpha)` (the
///   scipy documentation's `alpha = damp²` relation sklearn cites).
/// - `max_iter` `None` takes scipy's `2·d` `iter_lim` default. The Krylov space
///   is `d`-dimensional, so LSQR terminates exactly within that budget.
///
/// Returns `(coef, n_iter)`; `n_iter` is the iteration count sklearn surfaces
/// as `Ridge.n_iter_` for this solver.
pub fn lsqr(
    x: &[f64],
    y: &[f64],
    n: usize,
    d: usize,
    alpha: f64,
    tol: f64,
    max_iter: Option<usize>,
) -> (Vec<f64>, usize) {
    let iter_lim = max_iter.unwrap_or(2 * d).max(1);
    let damp = alpha.max(0.0).sqrt();

    let mut w_coef = vec![0.0f64; d];

    // --- Bidiagonalization seed: u = b/β, v = Xᵀu/α. ---
    let mut u = y.to_vec();
    let mut beta = dot(&u, &u).sqrt();
    if beta > 0.0 {
        for ui in u.iter_mut() {
            *ui /= beta;
        }
    } else {
        // b = 0 ⇒ the minimizer of ‖Xw‖² + α‖w‖² is w = 0.
        return (w_coef, 0);
    }
    let mut v = matvec_t(x, &u, n, d);
    let mut alfa = dot(&v, &v).sqrt();
    if alfa > 0.0 {
        for vi in v.iter_mut() {
            *vi /= alfa;
        }
    } else {
        return (w_coef, 0);
    }

    let mut w = v.clone();
    let mut rhobar = alfa;
    let mut phibar = beta;
    // scipy's `arnorm0` — the initial ‖Xᵀr‖ the relative stopping test uses.
    let arnorm0 = alfa * beta;

    let mut xv = vec![0.0f64; n];
    let mut n_iter = 0usize;
    for itn in 1..=iter_lim {
        n_iter = itn;

        // u ← X·v − α·u, normalized.
        matvec_into(x, &v, n, d, &mut xv);
        for i in 0..n {
            u[i] = xv[i] - alfa * u[i];
        }
        beta = dot(&u, &u).sqrt();
        if beta > 0.0 {
            for ui in u.iter_mut() {
                *ui /= beta;
            }
        }

        // v ← Xᵀ·u − β·v, normalized.
        let xtu = matvec_t(x, &u, n, d);
        for j in 0..d {
            v[j] = xtu[j] - beta * v[j];
        }
        alfa = dot(&v, &v).sqrt();
        if alfa > 0.0 {
            for vi in v.iter_mut() {
                *vi /= alfa;
            }
        }

        // --- The damping plane rotation (this is what turns plain LSQR into
        //     the RIDGE solve: it folds `damp·I` into the bidiagonal without
        //     ever materializing the stacked `[X; damp·I]` matrix). ---
        let rhobar1 = (rhobar * rhobar + damp * damp).sqrt();
        let cs1 = if rhobar1 > 0.0 { rhobar / rhobar1 } else { 1.0 };
        phibar *= cs1;

        // --- The Golub–Kahan plane rotation. ---
        let rho = (rhobar1 * rhobar1 + beta * beta).sqrt();
        if rho == 0.0 {
            break;
        }
        let cs = rhobar1 / rho;
        let sn = beta / rho;
        let theta = sn * alfa;
        rhobar = -cs * alfa;
        let phi = cs * phibar;
        phibar = sn * phibar;
        let tau = sn * phi;

        let t1 = phi / rho;
        let t2 = -theta / rho;
        for j in 0..d {
            w_coef[j] += t1 * w[j];
            w[j] = v[j] + t2 * w[j];
        }

        // scipy's `arnorm = alfa·|tau|` — the estimate of ‖Xᵀr − α·w‖ that its
        // `atol` test consumes. Relative form so `tol` means the same thing it
        // does for the other iterative arms.
        let arnorm = alfa * tau.abs();
        if arnorm0 > 0.0 && arnorm <= tol * arnorm0 {
            break;
        }
        if alfa == 0.0 || beta == 0.0 {
            // Krylov space exhausted — the solution is exact.
            break;
        }
    }
    (w_coef, n_iter)
}

/// Stochastic Average Gradient — the `solver='sag'` and `solver='saga'` arms.
///
/// sklearn routes both through `sag_solver(..., loss="squared", is_saga=...)`
/// with `alpha_scaled = alpha / n_samples`, minimizing
/// `(1/n)·Σᵢ wᵢ·½(xᵢ·β − yᵢ)² + (α/n)·½‖β‖²` — the same minimizer as Ridge's
/// `Σᵢ wᵢ(yᵢ − xᵢβ)² + α‖β‖²`, just scaled by `1/(2n)`.
///
/// The step size is reproduced EXACTLY from sklearn's `get_auto_step_size`
/// because it is the one constant that decides whether the iteration converges
/// at all (`_sag.py`, `loss == "squared"` branch):
///
/// ```text
/// L    = max_i ‖x_i‖² + int(fit_intercept) + alpha_scaled
/// sag  : step = 1 / L
/// saga : mun = min(2·n·alpha_scaled, L);  step = 1 / (2·L + mun)
/// ```
///
/// `fit_intercept` is `0` here: Ridge hands the solver an already-CENTERED
/// design and recovers the bias afterwards (`_preprocess_data` then
/// `_set_intercept`), so the intercept is never part of the stochastic system.
///
/// - `sw` is the per-sample weight (`None` ⇒ all ones). Unlike every other
///   solver, `sag`/`saga` take the weights DIRECTLY rather than through a
///   `sqrt(w)` row rescale — sklearn's `_ridge_regression` special-cases exactly
///   this (`if solver not in ["sag", "saga"]: X, y = _rescale_data(...)`).
/// - Convergence: sklearn's own epoch test, `max|Δβ| ≤ tol·max(1, max|β|)`.
/// - `max_iter` `None` takes sklearn's `sag_solver` default of `1000` epochs.
///
/// Returns `(coef, n_epochs)`; `n_epochs` is what sklearn reports as `n_iter_`.
#[allow(clippy::too_many_arguments)]
pub fn sag(
    x: &[f64],
    y: &[f64],
    sw: Option<&[f64]>,
    n: usize,
    d: usize,
    alpha: f64,
    tol: f64,
    max_iter: Option<usize>,
    seed: u64,
    is_saga: bool,
) -> (Vec<f64>, usize) {
    let max_iter = max_iter.unwrap_or(1000);
    let alpha_scaled = alpha / n as f64;

    // max_squared_sum = max_i ‖x_i‖² (sklearn's `row_norms(X, squared=True).max()`).
    let mut max_squared_sum = 0.0f64;
    for i in 0..n {
        let row = &x[i * d..(i + 1) * d];
        let s = dot(row, row);
        if s > max_squared_sum {
            max_squared_sum = s;
        }
    }
    let lipschitz = max_squared_sum + alpha_scaled;
    let step = if lipschitz <= 0.0 {
        // A degenerate all-zero design: every gradient is `alpha_scaled·β` and
        // β = 0 is already optimal. Any positive step is safe.
        1.0
    } else if is_saga {
        let mun = (2.0 * n as f64 * alpha_scaled).min(lipschitz);
        1.0 / (2.0 * lipschitz + mun)
    } else {
        1.0 / lipschitz
    };

    let mut beta = vec![0.0f64; d];
    let mut beta_prev = vec![0.0f64; d];
    // The gradient TABLE: one scalar `∂loss/∂p` per sample (the full per-sample
    // gradient is that scalar times the sample's row, so `d` floats per sample
    // never need storing).
    let mut grad_mem = vec![0.0f64; n];
    let mut seen = vec![false; n];
    let mut n_seen = 0usize;
    let mut sum_grad = vec![0.0f64; d];

    let mut rng = SplitMix64::new(seed);
    let mut epochs = 0usize;
    for epoch in 0..max_iter {
        epochs = epoch + 1;
        beta_prev.copy_from_slice(&beta);

        for _ in 0..n {
            let i = rng.index(n);
            if !seen[i] {
                seen[i] = true;
                n_seen += 1;
            }
            let row = &x[i * d..(i + 1) * d];
            let p = dot(row, &beta);
            let wi = sw.map_or(1.0, |w| w[i]);
            let g = wi * (p - y[i]);
            let g_old = grad_mem[i];
            grad_mem[i] = g;
            let dg = g - g_old;
            let inv_seen = 1.0 / n_seen as f64;

            if is_saga {
                // SAGA reads the table sum BEFORE the update and adds the
                // unbiased correction `(g − g_old)·x_i` (Defazio et al. 2014).
                for j in 0..d {
                    let grad_j = dg * row[j] + sum_grad[j] * inv_seen + alpha_scaled * beta[j];
                    beta[j] -= step * grad_j;
                }
                for j in 0..d {
                    sum_grad[j] += dg * row[j];
                }
            } else {
                // SAG steps along the UPDATED running average.
                for j in 0..d {
                    sum_grad[j] += dg * row[j];
                }
                for j in 0..d {
                    beta[j] -= step * (sum_grad[j] * inv_seen + alpha_scaled * beta[j]);
                }
            }
        }

        // sklearn's epoch stopping test (`_sag.py`: `max_change / max_weight`).
        let mut max_change = 0.0f64;
        let mut max_weight = 0.0f64;
        for j in 0..d {
            max_change = max_change.max((beta[j] - beta_prev[j]).abs());
            max_weight = max_weight.max(beta[j].abs());
        }
        if max_change <= tol * max_weight.max(1.0) {
            break;
        }
    }
    (beta, epochs)
}

/// Non-negative ridge by projected cyclic coordinate descent — the
/// `solver='lbfgs'` arm (`positive=True`).
///
/// sklearn's `_solve_lbfgs` hands `scipy.optimize.minimize(method="L-BFGS-B")`
/// the objective `½‖Xw − y‖² + ½α‖w‖²` with `bounds=[(0, inf)]·d`. That
/// objective is STRICTLY convex for `α > 0`, and the feasible set is a box, so
/// the constrained minimizer is UNIQUE — every correct bound-respecting solver
/// lands on the same point. This uses projected coordinate descent instead of
/// L-BFGS-B because each coordinate's exact constrained minimizer is available
/// in closed form off the Gram diagonal:
///
/// ```text
/// ∂f/∂w_j = (G·w)_j − (Xᵀy)_j + α·w_j        (G = XᵀX)
/// w_j ← max(0, w_j − ∂f/∂w_j / (G_jj + α))
/// ```
///
/// so a sweep is `O(d²)` on the ALREADY-COMPUTED device Gram and never touches
/// `X` — where L-BFGS-B would need an `O(n·d)` function+gradient evaluation per
/// line-search probe. The mlrs `lbfgs_minimize` prim is unconstrained
/// (`prims/lbfgs.rs`) and is deliberately NOT bent into a bound-constrained
/// solver here: projecting an L-BFGS iterate breaks its curvature history,
/// which is the standard reason L-BFGS-B needs its own gradient-projection
/// machinery.
///
/// - `gram` is the row-major `d×d` raw Gram; `xty` the length-`d` `Xᵀy`.
/// - Convergence: `max|Δw| ≤ tol·max(1, max|w|)`, the same shape as the SAG arm.
/// - `max_iter` `None` uses `1000` sweeps.
///
/// Returns `(coef, n_sweeps)`. sklearn leaves `n_iter_` at `None` for this
/// solver, so `ridge.rs` discards the count — it is returned only so the
/// caller can surface a non-convergence diagnostic.
pub fn nonnegative_cd(
    gram: &[f64],
    xty: &[f64],
    d: usize,
    alpha: f64,
    tol: f64,
    max_iter: Option<usize>,
) -> (Vec<f64>, usize) {
    let max_iter = max_iter.unwrap_or(1000);
    let mut w = vec![0.0f64; d];
    let mut sweeps = 0usize;

    for it in 0..max_iter {
        sweeps = it + 1;
        let mut max_change = 0.0f64;
        let mut max_weight = 0.0f64;
        for j in 0..d {
            let hess = gram[j * d + j] + alpha;
            if hess <= 0.0 {
                // A zero feature column with α = 0 leaves this coordinate
                // unconstrained by the data; 0 is a valid feasible minimizer.
                continue;
            }
            let row = &gram[j * d..(j + 1) * d];
            let grad = dot(row, &w) - xty[j] + alpha * w[j];
            let next = (w[j] - grad / hess).max(0.0);
            max_change = max_change.max((next - w[j]).abs());
            w[j] = next;
            max_weight = max_weight.max(next.abs());
        }
        if max_change <= tol * max_weight.max(1.0) {
            break;
        }
    }
    (w, sweeps)
}

/// `a·b` for equal-length host slices.
fn dot(a: &[f64], b: &[f64]) -> f64 {
    a.iter().zip(b.iter()).map(|(x, y)| x * y).sum()
}

/// `out ← X·v` for a row-major `n×d` `X`.
fn matvec_into(x: &[f64], v: &[f64], n: usize, d: usize, out: &mut [f64]) {
    for i in 0..n {
        out[i] = dot(&x[i * d..(i + 1) * d], v);
    }
}

/// `Xᵀ·u` for a row-major `n×d` `X` (no transpose buffer — the row-major walk
/// accumulates straight into the length-`d` output).
fn matvec_t(x: &[f64], u: &[f64], n: usize, d: usize) -> Vec<f64> {
    let mut out = vec![0.0f64; d];
    for i in 0..n {
        let ui = u[i];
        if ui == 0.0 {
            continue;
        }
        let row = &x[i * d..(i + 1) * d];
        for j in 0..d {
            out[j] += ui * row[j];
        }
    }
    out
}
