//! scikit-learn oracle `.npz` fixture loader (D-01 / D-02 / D-03).
//!
//! Oracle fixtures are committed `.npz` archives of named arrays (e.g. `X`,
//! `y`, `coef_`, `intercept_`, or `a`/`x`/`y`/`expected` for the saxpy smoke
//! case). They are generated by `scripts/gen_oracle.py` (NumPy
//! `default_rng(seed)`) so the reference matches sklearn exactly, and read here
//! at test time with **no Python** in the loop.
//!
//! Reading uses `npyz`'s `NpzArchive::by_name` (resolved in `SPIKE-FINDINGS.md`
//! §A4) — we do NOT hand-roll zip + npy-header parsing.

use std::io::{Read, Seek};
use std::path::Path;

use npyz::npz::NpzArchive;

/// A loaded oracle fixture: named arrays read by name, decodable to `f32` or
/// `f64`. Arrays are stored as their flat element buffer plus the original
/// shape so a caller can reshape as needed.
pub struct OracleCase {
    archive_path: String,
    raw: std::collections::HashMap<String, RawArray>,
}

/// One decoded array: the flat `f64` values (npy decodes both f32 and f64
/// through `into_vec::<f64>()` losslessly for the dtypes we emit) plus shape.
struct RawArray {
    shape: Vec<u64>,
    values_f64: Vec<f64>,
    values_f32: Vec<f32>,
}

impl OracleCase {
    /// Names of every array present in the fixture.
    pub fn names(&self) -> Vec<&str> {
        self.raw.keys().map(|s| s.as_str()).collect()
    }

    /// Path the fixture was loaded from (for diagnostics).
    pub fn path(&self) -> &str {
        &self.archive_path
    }

    /// Returns the named array as `f64`, or `None` if absent.
    pub fn f64(&self, name: &str) -> Option<&[f64]> {
        self.raw.get(name).map(|a| a.values_f64.as_slice())
    }

    /// Returns the named array as `f32`, or `None` if absent.
    pub fn f32(&self, name: &str) -> Option<&[f32]> {
        self.raw.get(name).map(|a| a.values_f32.as_slice())
    }

    /// Returns the shape of the named array, or `None` if absent.
    pub fn shape(&self, name: &str) -> Option<&[u64]> {
        self.raw.get(name).map(|a| a.shape.as_slice())
    }

    /// Returns the named `f64` array, panicking with a clear message if absent.
    pub fn expect_f64(&self, name: &str) -> &[f64] {
        self.f64(name)
            .unwrap_or_else(|| panic!("oracle fixture '{}' has no array '{name}'", self.archive_path))
    }

    /// Returns the named `f32` array, panicking with a clear message if absent.
    pub fn expect_f32(&self, name: &str) -> &[f32] {
        self.f32(name)
            .unwrap_or_else(|| panic!("oracle fixture '{}' has no array '{name}'", self.archive_path))
    }
}

/// Loads an oracle `.npz` fixture from `path`, decoding every named array into
/// both an `f32` and an `f64` view so callers can compare at either precision.
///
/// Errors are surfaced as [`npyz`]'s `io::Error` (the npz crate's failure
/// type), not a hand-rolled parser error.
pub fn load_npz<P: AsRef<Path>>(path: P) -> std::io::Result<OracleCase> {
    let path_ref = path.as_ref();
    let archive_path = path_ref.display().to_string();
    let mut npz = NpzArchive::open(path_ref)?;
    let names: Vec<String> = npz.array_names().map(|s| s.to_string()).collect();
    read_named_arrays(&mut npz, &names, archive_path)
}

/// Loads an oracle fixture from any in-memory reader (used by tests that build
/// a throwaway `.npz` with the `npyz` writer, no file on disk).
pub fn load_npz_reader<R: Read + Seek>(
    reader: R,
    label: impl Into<String>,
) -> std::io::Result<OracleCase> {
    let archive_path = label.into();
    let mut npz = NpzArchive::new(reader)?;
    let names: Vec<String> = npz.array_names().map(|s| s.to_string()).collect();
    read_named_arrays(&mut npz, &names, archive_path)
}

fn read_named_arrays<R: Read + Seek>(
    npz: &mut NpzArchive<R>,
    names: &[String],
    archive_path: String,
) -> std::io::Result<OracleCase> {
    let mut raw = std::collections::HashMap::new();
    for name in names {
        // by_name -> Result<Option<NpyFile>, io::Error>; None means absent.
        let entry = npz.by_name(name)?;
        let arr = match entry {
            Some(a) => a,
            None => continue,
        };
        let shape = arr.shape().to_vec();
        // npyz's typed reader is STRICT: `into_vec::<f64>()` only succeeds on an
        // 8-byte float dtype and `into_vec::<f32>()` only on a 4-byte one
        // (npyz-0.9.1 serialize/primitive.rs). So we branch on the stored byte
        // width, decode at the native precision, and derive the other view.
        let num_bytes = arr.dtype().num_bytes();
        let (values_f32, values_f64): (Vec<f32>, Vec<f64>) = match num_bytes {
            Some(8) => {
                let v64: Vec<f64> = arr.into_vec::<f64>()?;
                let v32: Vec<f32> = v64.iter().map(|&v| v as f32).collect();
                (v32, v64)
            }
            Some(4) => {
                let v32: Vec<f32> = arr.into_vec::<f32>()?;
                let v64: Vec<f64> = v32.iter().map(|&v| v as f64).collect();
                (v32, v64)
            }
            other => {
                return Err(std::io::Error::new(
                    std::io::ErrorKind::InvalidData,
                    format!(
                        "oracle array '{name}' in '{archive_path}' is not a 4- or 8-byte \
                         float (num_bytes = {other:?}); only f32/f64 fixtures are supported"
                    ),
                ));
            }
        };
        raw.insert(
            name.clone(),
            RawArray {
                shape,
                values_f64,
                values_f32,
            },
        );
    }
    Ok(OracleCase { archive_path, raw })
}
