//! AGGLO-01 — AgglomerativeClustering (single-linkage) sklearn oracle gates.
//!
//! Each gate loads a committed `agglomerative_{metric}_{dtype}_seed42.npz`
//! fixture (sklearn 1.9.0, generated by `scripts/gen_oracle.py`) and asserts
//! EXACT equality — no permutation matching: mlrs ports the unstructured
//! single-linkage pipeline line-for-line (`mst_linkage_core`, the sklearn /
//! scipy union-find labelling pair, and `_hc_cut` including the Python-heapq
//! array order), so `labels_` and `children_` must match sklearn bit-for-bit
//! on the tie-free fixture design:
//!
//!   - `children_match_sklearn` — the (n-1)×2 dendrogram rows are exactly
//!     sklearn's `children_`, per metric × dtype.
//!   - `labels_match_sklearn` — `labels_` at n_clusters ∈ {2, 3, 5} are exactly
//!     sklearn's, per metric × dtype (the k=5 cut exercises repeated
//!     heappush/heappushpop layout).
//!   - `build_validation` — `n_clusters = 0` is rejected at build (D-08).
//!   - `fit_validation` — `n_clusters > n_samples` and `n_samples < 2` are
//!     rejected at fit with typed errors BEFORE any launch.
//!   - `fitted_surface` — `n_leaves_` / `n_connected_components_` /
//!     `n_clusters_` / `n_features_in_` carry the sklearn values.
//!
//! f64 cases carry the `skip_f64_with_log` capability gate verbatim (cpu runs
//! f64; rocm skips per the CubeCL-HIP F64 gap). Per AGENTS.md §2 tests live in
//! `crates/mlrs-algos/tests/`, never an in-source `#[cfg(test)] mod tests`.

use std::path::PathBuf;

use bytemuck::Pod;
use cubecl::prelude::{CubeElement, Float};

use mlrs_algos::cluster::agglomerative::{AgglomerativeClustering, Metric};
use mlrs_algos::error::{AlgoError, BuildError};
use mlrs_algos::typestate::Fit;
use mlrs_backend::capability;
use mlrs_backend::device_array::DeviceArray;
use mlrs_backend::pool::BufferPool;
use mlrs_backend::runtime::{self, ActiveRuntime};
use mlrs_core::{load_npz, OracleCase};

/// Fixture geometry (gen_oracle.py `gen_agglomerative`: 3 blobs × 20 × 5).
const AGG_N_SAMPLES: usize = 60;
const AGG_N_FEATURES: usize = 5;

fn fixture(name: &str) -> PathBuf {
    let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let workspace_root = manifest
        .parent()
        .and_then(|p| p.parent())
        .expect("workspace root is two levels above the crate manifest dir");
    workspace_root.join("tests").join("fixtures").join(name)
}

fn f64_to<F: Pod>(v: f64) -> F {
    match std::mem::size_of::<F>() {
        4 => *bytemuck::from_bytes::<F>(bytemuck::bytes_of(&(v as f32))),
        8 => *bytemuck::from_bytes::<F>(bytemuck::bytes_of(&v)),
        _ => unreachable!("agglomerative fixtures are f32/f64 only"),
    }
}

/// Fit at `n_clusters` on the fixture design and return `(labels, children)`.
fn fit_agglomerative<F>(
    case: &OracleCase,
    metric: Metric,
    n_clusters: usize,
) -> (Vec<i32>, Vec<[i64; 2]>)
where
    F: Float + CubeElement + Pod,
{
    let client = runtime::active_client();
    let mut pool: BufferPool<ActiveRuntime> = BufferPool::new(client);

    let x_host: Vec<F> = case
        .expect_f64("X")
        .iter()
        .map(|&v| f64_to::<F>(v))
        .collect();
    let x_dev: DeviceArray<ActiveRuntime, F> = DeviceArray::from_host(&mut pool, &x_host);

    let model = AgglomerativeClustering::<F>::builder()
        .n_clusters(n_clusters)
        .metric(metric)
        .build::<F>()
        .expect("AgglomerativeClustering build with valid hyperparameters");
    let model = model
        .fit(&mut pool, &x_dev, None, (AGG_N_SAMPLES, AGG_N_FEATURES))
        .expect("AgglomerativeClustering::fit on a valid shape");

    let labels = model.labels(&pool);
    let children = model.children().to_vec();
    (labels, children)
}

/// EXACT children + labels equality per fixture (see module docs).
fn run_case<F>(metric: Metric, metric_tag: &str, dtype_tag: &str)
where
    F: Float + CubeElement + Pod,
{
    let name = format!("agglomerative_{metric_tag}_{dtype_tag}_seed42.npz");
    let case = load_npz(&fixture(&name)).expect("fixture loads");

    let children_ref: Vec<[i64; 2]> = case
        .expect_f64("children")
        .chunks(2)
        .map(|c| [c[0] as i64, c[1] as i64])
        .collect();
    assert_eq!(
        children_ref.len(),
        AGG_N_SAMPLES - 1,
        "fixture children rows"
    );

    for (k, key) in [(2usize, "labels_k2"), (3, "labels_k3"), (5, "labels_k5")] {
        let labels_ref: Vec<i32> = case.expect_f64(key).iter().map(|&v| v as i32).collect();
        let (labels, children) = fit_agglomerative::<F>(&case, metric, k);
        assert_eq!(
            children, children_ref,
            "{name} k={k}: children_ must EXACTLY match sklearn"
        );
        assert_eq!(
            labels, labels_ref,
            "{name} k={k}: labels_ must EXACTLY match sklearn"
        );
    }
}

// --- children + labels, per metric × dtype ---------------------------------

#[test]
fn labels_and_children_euclidean_f32() {
    run_case::<f32>(Metric::Euclidean, "euclidean", "f32");
}

#[test]
fn labels_and_children_euclidean_f64() {
    if capability::skip_f64_with_log() {
        return;
    }
    run_case::<f64>(Metric::Euclidean, "euclidean", "f64");
}

#[test]
fn labels_and_children_manhattan_f32() {
    run_case::<f32>(Metric::Manhattan, "manhattan", "f32");
}

#[test]
fn labels_and_children_manhattan_f64() {
    if capability::skip_f64_with_log() {
        return;
    }
    run_case::<f64>(Metric::Manhattan, "manhattan", "f64");
}

#[test]
fn labels_and_children_cosine_f32() {
    run_case::<f32>(Metric::Cosine, "cosine", "f32");
}

#[test]
fn labels_and_children_cosine_f64() {
    if capability::skip_f64_with_log() {
        return;
    }
    run_case::<f64>(Metric::Cosine, "cosine", "f64");
}

// --- validation ------------------------------------------------------------

#[test]
fn build_validation() {
    // n_clusters = 0 → typed BuildError (data-INDEPENDENT, D-08).
    let err = match AgglomerativeClustering::<f32>::builder()
        .n_clusters(0)
        .build::<f32>()
    {
        Err(e) => e,
        Ok(_) => panic!("n_clusters = 0 must be rejected at build"),
    };
    assert!(
        matches!(err, BuildError::InvalidNClusters { n_clusters: 0, .. }),
        "expected InvalidNClusters, got {err:?}"
    );
}

#[test]
fn fit_validation() {
    let client = runtime::active_client();
    let mut pool: BufferPool<ActiveRuntime> = BufferPool::new(client);

    // n_clusters > n_samples → AlgoError::InvalidK BEFORE any launch.
    let x: Vec<f32> = vec![0.0, 0.0, 1.0, 1.0, 2.0, 2.0]; // 3 × 2
    let x_dev: DeviceArray<ActiveRuntime, f32> = DeviceArray::from_host(&mut pool, &x);
    let model = AgglomerativeClustering::<f32>::builder()
        .n_clusters(4)
        .build::<f32>()
        .expect("valid build");
    let err = model
        .fit(&mut pool, &x_dev, None, (3, 2))
        .err()
        .expect("n_clusters > n_samples must be rejected at fit");
    assert!(
        matches!(
            err,
            AlgoError::InvalidK {
                k: 4,
                n_samples: 3,
                ..
            }
        ),
        "expected InvalidK, got {err:?}"
    );

    // n_samples < 2 → typed shape error (sklearn ensure_min_samples=2).
    let x1: Vec<f32> = vec![0.0, 0.0];
    let x1_dev: DeviceArray<ActiveRuntime, f32> = DeviceArray::from_host(&mut pool, &x1);
    let model = AgglomerativeClustering::<f32>::builder()
        .n_clusters(1)
        .build::<f32>()
        .expect("valid build");
    assert!(
        model.fit(&mut pool, &x1_dev, None, (1, 2)).is_err(),
        "a 1-sample fit must be rejected"
    );
}

// --- fitted surface --------------------------------------------------------

#[test]
fn fitted_surface() {
    let case = load_npz(&fixture("agglomerative_euclidean_f32_seed42.npz")).expect("fixture loads");
    let client = runtime::active_client();
    let mut pool: BufferPool<ActiveRuntime> = BufferPool::new(client);

    let x_host: Vec<f32> = case.expect_f64("X").iter().map(|&v| v as f32).collect();
    let x_dev: DeviceArray<ActiveRuntime, f32> = DeviceArray::from_host(&mut pool, &x_host);

    let model = AgglomerativeClustering::<f32>::builder()
        .n_clusters(3)
        .build::<f32>()
        .expect("valid build")
        .fit(&mut pool, &x_dev, None, (AGG_N_SAMPLES, AGG_N_FEATURES))
        .expect("valid fit");

    assert_eq!(model.n_clusters(), 3);
    assert_eq!(model.n_leaves(), AGG_N_SAMPLES);
    assert_eq!(model.n_connected_components(), 1);
    assert_eq!(model.n_features_in(), AGG_N_FEATURES);
    assert_eq!(model.children().len(), AGG_N_SAMPLES - 1);
}
