//! Plan 15-02 Wave-0 — HDBSCAN (HDBS-01..04) oracle gate suite.
//!
//! This REPLACES the Phase-12 shell convention tests with the full Nyquist gate
//! suite each later HDBSCAN wave turns green. Every gate loads a committed
//! `hdbscan_*.npz` oracle fixture (generated by `scripts/gen_oracle.py` against
//! `sklearn.cluster.HDBSCAN` 1.9.0 + `hdbscan` 0.8.44 — see that file for the
//! design rationale; no Python at test time) and asserts the fitted estimator vs
//! the oracle:
//!
//!   - `labels_match_sklearn` — per metric × {f32,f64}, fitted `labels_` is a
//!     `-1`-PINNED permutation of sklearn's (`best_match_accuracy_pinned_noise
//!     == 1.0`, HDBS-02 / D-03).
//!   - `tie_break_exact` — the tie-heavy + duplicate-point fixture (D-04 TRUE
//!     GATE): same pinned-noise gate over an adversarial tie-heavy MST design,
//!     and the duplicate row (R-9) must share its partner's label.
//!   - `probabilities_match` — per-point `probabilities_` vs sklearn ≤1e-5
//!     (HDBS-01 / D-06).
//!   - `outlier_scores_match` — per-point GLOSH `outlier_scores_` vs hdbscan
//!     0.8.44 ≤1e-5 (HDBS-03 / D-07).
//!   - `centers_match` — `centroids_`/`medoids_` vs sklearn ≤1e-5 under the SAME
//!     label permutation (HDBS-04 / Pitfall 6).
//!   - `selection_knobs` — the nested-density fixture's non-default eom/leaf/
//!     epsilon/max_cluster_size/alpha label vectors are each an exact pinned-noise
//!     permutation of the corresponding oracle (HDBS-01 / D-09).
//!   - `build_validation` — `min_cluster_size`/`min_samples`/`max_cluster_size`/
//!     `alpha`/minkowski-`p` are rejected at build (data-independent, D-08).
//!   - `memory_gate` — re-construct + re-fit does not grow `live_bytes`, and the
//!     device front-end keeps `peak_bytes` sub-quadratic (no `n×n` resident).
//!   - `edge_cases` — all-noise / single-cluster / n<min_cluster_size match
//!     sklearn.
//!
//! WAVE-0 STATUS: the back-end algorithm is NOT built yet — the shell `fit` is
//! still trivial and the extended `Metric`, score/center accessors, and
//! non-Euclidean metrics do not exist. Gates that depend on those symbols are
//! `#[ignore]`d with a `// un-ignore in 15-NN` marker; their bodies are written
//! to COMPILE against the current shell (they load the fixture and exercise the
//! pinned-noise matcher / `assert_close` helper on the oracle arrays as a
//! self-consistency placeholder) so the file compiles green in Wave 0. The later
//! waves replace each placeholder body with the real fit-vs-oracle comparison and
//! drop the `#[ignore]`. `build_validation` runs NOW (the build path exists).
//!
//! f64 cases carry the `skip_f64_with_log` capability gate verbatim (cpu runs
//! f64; rocm skips per the CubeCL-HIP F64 gap). Per AGENTS.md §2 tests live in
//! `crates/mlrs-algos/tests/`, never an in-source `#[cfg(test)] mod tests`.

use std::path::PathBuf;

use mlrs_algos::cluster::hdbscan::{Hdbscan, Metric};
use mlrs_algos::error::BuildError;
use mlrs_backend::capability;
use mlrs_core::{
    best_mapping, best_match_accuracy_pinned_noise, load_npz, OracleCase, Tolerance, F32_TOL,
    F64_TOL,
};

// ---------------------------------------------------------------------------
// Fixture loader + cast/compare helpers (copied verbatim from kmeans_test.rs so
// the oracle plumbing is identical across estimators).
// ---------------------------------------------------------------------------

/// Resolve `<workspace_root>/tests/fixtures/<name>` (the committed-blob dir).
fn fixture(name: &str) -> PathBuf {
    let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let workspace_root = manifest
        .parent()
        .and_then(|p| p.parent())
        .expect("workspace root is two levels above the crate manifest dir");
    workspace_root.join("tests").join("fixtures").join(name)
}

/// numpy-`allclose` element compare: pass if `|got − exp| ≤ atol + rtol·|exp|`
/// (abs-OR-rel), the strict 1e-5 ABSOLUTE arm never loosened.
fn assert_close(got: &[f64], expected: &[f64], tol: &Tolerance, what: &str) {
    assert_eq!(
        got.len(),
        expected.len(),
        "{what}: length mismatch got={} expected={}",
        got.len(),
        expected.len()
    );
    for (i, (&g, &e)) in got.iter().zip(expected.iter()).enumerate() {
        let abs_err = (g - e).abs();
        let allclose = abs_err <= tol.abs + tol.rel * e.abs();
        assert!(
            allclose,
            "{what}: allclose failed at {i}: got={g:e} expected={e:e} \
             abs_err={abs_err:e} (atol={:e}, rtol={:e})",
            tol.abs, tol.rel
        );
    }
}

/// Read a fixture's float-valued label array as `i64` (load_npz decodes only
/// 4/8-byte float arrays, so labels are stored float-valued — kmeans_test.rs:133).
fn labels_i64(case: &OracleCase, name: &str) -> Vec<i64> {
    case.expect_f64(name).iter().map(|&v| v as i64).collect()
}

/// The f64 capability gate (verbatim from kmeans_test.rs:183-189): cpu runs f64,
/// rocm skips-with-log per the CubeCL-HIP F64 gap. Returns `true` when the caller
/// should early-return.
fn skip_f64(test: &str) -> bool {
    let backend = capability::active_backend_name();
    capability::log_oracle_dtype(capability::FloatKind::F64, backend, "default");
    if capability::skip_f64_with_log() {
        println!("hdbscan {test} f64 backend={backend}: SKIPPED (no f64 support on this adapter)");
        return true;
    }
    false
}

// ---------------------------------------------------------------------------
// Precomputed-path fit helpers (plan 15-04). The host tree back-end is wired only
// for `Metric::Precomputed` in this wave (the feature-metric device front-end
// lands in 15-05). Both gate helpers therefore route through the precomputed
// path: the `precomputed` fixture ships an n×n distance matrix directly, while the
// euclidean/nested/edge fixtures ship feature `X` — we build the EXACT euclidean
// pairwise distance matrix host-side (precomputed-euclidean == euclidean for
// labels/probabilities, since the oracle's precomputed fixture is exactly
// `pairwise_distances(X, 'euclidean')` of the same design). Builder knobs
// (min_cluster_size, selection method, epsilon, max_cluster_size, alpha,
// allow_single_cluster) are threaded through so every D-09 knob exercises the real
// selection code.
// ---------------------------------------------------------------------------

use mlrs_algos::cluster::hdbscan::ClusterSelectionMethod;
use mlrs_algos::typestate::Fit;
use mlrs_backend::device_array::DeviceArray;
use mlrs_backend::pool::BufferPool;
use mlrs_backend::runtime::{self, ActiveRuntime};

/// Knob bundle for a precomputed-path fit (defaults mirror sklearn).
#[derive(Clone, Copy)]
struct FitKnobs {
    min_cluster_size: usize,
    min_samples: Option<usize>,
    method: ClusterSelectionMethod,
    epsilon: f64,
    max_cluster_size: usize,
    alpha: f64,
    allow_single_cluster: bool,
}

impl FitKnobs {
    fn defaults(min_cluster_size: usize) -> Self {
        Self {
            min_cluster_size,
            min_samples: None,
            method: ClusterSelectionMethod::Eom,
            epsilon: 0.0,
            max_cluster_size: 0,
            alpha: 1.0,
            allow_single_cluster: false,
        }
    }
}

/// Dense euclidean pairwise distance matrix (row-major `n×n`) from feature rows
/// `x` of shape `(n, d)`. Matches `sklearn.metrics.pairwise_distances(X,
/// 'euclidean')` exactly (the oracle's precomputed-fixture construction).
fn euclidean_distance_matrix(x: &[f64], n: usize, d: usize) -> Vec<f64> {
    let mut dist = vec![0.0f64; n * n];
    for i in 0..n {
        for j in 0..n {
            let mut s = 0.0f64;
            for k in 0..d {
                let diff = x[i * d + k] - x[j * d + k];
                s += diff * diff;
            }
            dist[i * n + j] = s.sqrt();
        }
    }
    dist
}

/// Fit `Hdbscan` over a precomputed `n×n` distance matrix `dist` with the given
/// knobs; return `(labels, probabilities)` host-side. Pure precomputed path.
fn fit_precomputed(dist: &[f64], n: usize, knobs: FitKnobs) -> (Vec<i64>, Vec<f64>) {
    let client = runtime::active_client();
    let mut pool: BufferPool<ActiveRuntime> = BufferPool::new(client);
    let x_dev: DeviceArray<ActiveRuntime, f64> = DeviceArray::from_host(&mut pool, dist);

    let fitted = Hdbscan::<f64>::builder()
        .min_cluster_size(knobs.min_cluster_size)
        .min_samples(knobs.min_samples)
        .cluster_selection_method(knobs.method)
        .cluster_selection_epsilon(knobs.epsilon)
        .max_cluster_size(knobs.max_cluster_size)
        .alpha(knobs.alpha)
        .allow_single_cluster(knobs.allow_single_cluster)
        .metric(Metric::Precomputed)
        .build::<f64>()
        .expect("build precomputed")
        .fit(&mut pool, &x_dev, None, (n, n))
        .expect("precomputed fit");

    let labels: Vec<i64> = fitted.labels(&pool).iter().map(|&l| l as i64).collect();
    let probs = fitted
        .probabilities(&pool)
        .expect("precomputed fit produces probabilities");
    (labels, probs)
}

/// Fit over a feature matrix `x` of shape `(n, d)` by first building its euclidean
/// distance matrix and routing through the precomputed path (== euclidean fit).
fn fit_euclidean_via_precomputed(x: &[f64], n: usize, d: usize, knobs: FitKnobs) -> (Vec<i64>, Vec<f64>) {
    let dist = euclidean_distance_matrix(x, n, d);
    fit_precomputed(&dist, n, knobs)
}

/// Fit `Hdbscan` over a FEATURE matrix `x` of shape `(n, d)` under `metric` via the
/// real device front-end (plan 15-05): the KNN-prim core distances + Variant-A
/// (cosine) / Variant-B (the other four) MST → host back-end. Returns
/// `(labels, probabilities)` host-side. The `f64` path runs on cpu; rocm skips f64
/// at the call site.
fn fit_feature_metric<F>(x: &[f64], n: usize, d: usize, metric: Metric, knobs: FitKnobs) -> (Vec<i64>, Vec<f64>)
where
    F: cubecl::prelude::Float + cubecl::prelude::CubeElement + bytemuck::Pod,
{
    let client = runtime::active_client();
    let mut pool: BufferPool<ActiveRuntime> = BufferPool::new(client);
    let x_f: Vec<F> = x
        .iter()
        .map(|&v| match std::mem::size_of::<F>() {
            4 => *bytemuck::from_bytes::<F>(bytemuck::bytes_of(&(v as f32))),
            8 => *bytemuck::from_bytes::<F>(bytemuck::bytes_of(&v)),
            _ => unreachable!("f32/f64 only"),
        })
        .collect();
    let x_dev: DeviceArray<ActiveRuntime, F> = DeviceArray::from_host(&mut pool, &x_f);

    let fitted = Hdbscan::<F>::builder()
        .min_cluster_size(knobs.min_cluster_size)
        .min_samples(knobs.min_samples)
        .cluster_selection_method(knobs.method)
        .cluster_selection_epsilon(knobs.epsilon)
        .max_cluster_size(knobs.max_cluster_size)
        .alpha(knobs.alpha)
        .allow_single_cluster(knobs.allow_single_cluster)
        .metric(metric)
        .build::<F>()
        .expect("build feature metric")
        .fit(&mut pool, &x_dev, None, (n, d))
        .expect("feature-metric fit");

    let labels: Vec<i64> = fitted.labels(&pool).iter().map(|&l| l as i64).collect();
    let probs_f: Vec<F> = fitted
        .probabilities(&pool)
        .expect("feature-metric fit produces probabilities");
    let probs: Vec<f64> = probs_f
        .iter()
        .map(|&v| match std::mem::size_of::<F>() {
            4 => *bytemuck::from_bytes::<f32>(bytemuck::bytes_of(&v)) as f64,
            8 => *bytemuck::from_bytes::<f64>(bytemuck::bytes_of(&v)),
            _ => unreachable!("f32/f64 only"),
        })
        .collect();
    (labels, probs)
}

/// Fit `Hdbscan` over a FEATURE matrix `x` of shape `(n, d)` under Euclidean (the
/// blob fixture's metric) via the real device front-end (plan 15-05) and return the
/// fitted GLOSH `outlier_scores_` host-side (HDBS-03, plan 15-06). The GLOSH score
/// is per-point (no permutation needed for the compare). `f64` runs on cpu; rocm
/// skips f64 at the call site.
fn fit_outlier_scores<F>(x: &[f64], n: usize, d: usize, knobs: FitKnobs) -> Vec<f64>
where
    F: cubecl::prelude::Float + cubecl::prelude::CubeElement + bytemuck::Pod,
{
    let client = runtime::active_client();
    let mut pool: BufferPool<ActiveRuntime> = BufferPool::new(client);
    let x_f: Vec<F> = x
        .iter()
        .map(|&v| match std::mem::size_of::<F>() {
            4 => *bytemuck::from_bytes::<F>(bytemuck::bytes_of(&(v as f32))),
            8 => *bytemuck::from_bytes::<F>(bytemuck::bytes_of(&v)),
            _ => unreachable!("f32/f64 only"),
        })
        .collect();
    let x_dev: DeviceArray<ActiveRuntime, F> = DeviceArray::from_host(&mut pool, &x_f);

    let fitted = Hdbscan::<F>::builder()
        .min_cluster_size(knobs.min_cluster_size)
        .min_samples(knobs.min_samples)
        .cluster_selection_method(knobs.method)
        .cluster_selection_epsilon(knobs.epsilon)
        .max_cluster_size(knobs.max_cluster_size)
        .alpha(knobs.alpha)
        .allow_single_cluster(knobs.allow_single_cluster)
        .metric(Metric::Euclidean)
        .build::<F>()
        .expect("build euclidean")
        .fit(&mut pool, &x_dev, None, (n, d))
        .expect("euclidean fit");

    let scores_f: Vec<F> = fitted
        .outlier_scores(&pool)
        .expect("fit produces outlier_scores");
    scores_f
        .iter()
        .map(|&v| match std::mem::size_of::<F>() {
            4 => *bytemuck::from_bytes::<f32>(bytemuck::bytes_of(&v)) as f64,
            8 => *bytemuck::from_bytes::<f64>(bytemuck::bytes_of(&v)),
            _ => unreachable!("f32/f64 only"),
        })
        .collect()
}

/// The estimator [`Metric`] for a fixture tag (the per-metric label gate). Minkowski
/// carries the fixture's `HDB_MINKOWSKI_P = 3.0` (gen_oracle.py).
fn metric_for(tag: &str) -> Metric {
    match tag {
        "euclidean" => Metric::Euclidean,
        "manhattan" => Metric::Manhattan,
        "cosine" => Metric::Cosine,
        "chebyshev" => Metric::Chebyshev,
        "minkowski" => Metric::Minkowski { p: 3.0 },
        _ => panic!("unknown metric tag {tag}"),
    }
}

// ---------------------------------------------------------------------------
// HDBS-02 / D-03: labels match sklearn exactly up to a -1-pinned permutation,
// per metric × {f32, f64}. The exact-label gate uses the PINNED-NOISE matcher so
// a noise/cluster mismatch is a genuine failure (never permuted away).
//
// WAVE-0: the shell `Metric` has only `Euclidean` and `fit` is trivial, so the
// real fit-vs-oracle comparison cannot run yet. Each gate loads its fixture and
// invokes `best_match_accuracy_pinned_noise` on the oracle's own
// sklearn-vs-hdbscan label pair as a self-consistency placeholder that exercises
// the exact matcher this gate will use. Un-ignore + swap to the fitted labels in
// 15-NN.
// ---------------------------------------------------------------------------

/// The per-metric feature-fixture geometry (all five share the `blobs` design:
/// HDB_BLOB_N_FEATURES = 4, mcs = HDB_MIN_CLUSTER_SIZE = 5 — gen_oracle.py).
const HDB_METRIC_N_FEATURES: usize = 4;

/// Real feature-metric label gate body (plan 15-05): fit the feature `X` under
/// `metric` via the device front-end, assert the fitted labels are a -1-pinned
/// permutation of sklearn's. `run_labels_feature::<F>` is monomorphised per dtype.
fn run_labels_feature<F>(case: &OracleCase, tag: &str, label: &str)
where
    F: cubecl::prelude::Float + cubecl::prelude::CubeElement + bytemuck::Pod,
{
    let sklearn = labels_i64(case, "labels");
    let n = sklearn.len();
    let x: Vec<f64> = case.expect_f64("X").to_vec();
    let (got, _probs) = fit_feature_metric::<F>(
        &x,
        n,
        HDB_METRIC_N_FEATURES,
        metric_for(tag),
        FitKnobs::defaults(HDB_BLOB_MCS),
    );
    let acc = best_match_accuracy_pinned_noise(&got, &sklearn);
    assert!(
        (acc - 1.0).abs() < f64::EPSILON,
        "{label}: labels not a -1-pinned permutation of sklearn (acc={acc})\n got={got:?}\n exp={sklearn:?}"
    );
}

macro_rules! labels_match_metric {
    ($f32_name:ident, $f64_name:ident, $metric:literal) => {
        #[test]
        fn $f32_name() {
            let backend = capability::active_backend_name();
            capability::log_oracle_dtype(capability::FloatKind::F32, backend, "default");
            let case = load_npz(fixture(concat!("hdbscan_", $metric, "_f32_seed42.npz")))
                .expect(concat!("load hdbscan_", $metric, "_f32"));
            run_labels_feature::<f32>(&case, $metric, concat!("labels_match_sklearn ", $metric, " f32"));
        }

        #[test]
        fn $f64_name() {
            if skip_f64(concat!("labels_match_sklearn ", $metric)) {
                return;
            }
            let case = load_npz(fixture(concat!("hdbscan_", $metric, "_f64_seed42.npz")))
                .expect(concat!("load hdbscan_", $metric, "_f64"));
            run_labels_feature::<f64>(&case, $metric, concat!("labels_match_sklearn ", $metric, " f64"));
        }
    };
}

// A single `labels_match_sklearn` driver per metric × dtype (HDBS-02). The
// function name `labels_match_sklearn_*` keeps the VALIDATION targeted-run command
// `cargo test ... labels_match_sklearn` selecting the whole family.
labels_match_metric!(
    labels_match_sklearn_euclidean_f32,
    labels_match_sklearn_euclidean_f64,
    "euclidean"
);
labels_match_metric!(
    labels_match_sklearn_manhattan_f32,
    labels_match_sklearn_manhattan_f64,
    "manhattan"
);
labels_match_metric!(
    labels_match_sklearn_cosine_f32,
    labels_match_sklearn_cosine_f64,
    "cosine"
);
labels_match_metric!(
    labels_match_sklearn_chebyshev_f32,
    labels_match_sklearn_chebyshev_f64,
    "chebyshev"
);
labels_match_metric!(
    labels_match_sklearn_minkowski_f32,
    labels_match_sklearn_minkowski_f64,
    "minkowski"
);
// The precomputed metric is the ONLY end-to-end-fittable path in plan 15-04 (the
// feature-metric device front-end lands in 15-05), so its label gate runs the REAL
// fit (not the Wave-0 oracle self-consistency placeholder). The precomputed
// fixture's `X` is the n×n euclidean distance matrix of the `blobs` design;
// min_cluster_size = HDB_MIN_CLUSTER_SIZE = 5, eom default.
const HDB_BLOB_MCS: usize = 5;

/// `labels_match_sklearn` precomputed f32 — the real precomputed-path fit's labels
/// are a -1-pinned permutation of sklearn's (HDBS-02 / D-03).
#[test]
fn labels_match_sklearn_precomputed_f32() {
    let backend = capability::active_backend_name();
    capability::log_oracle_dtype(capability::FloatKind::F32, backend, "default");
    run_precomputed_labels("f32", "labels_match_sklearn precomputed f32");
}

/// `labels_match_sklearn` precomputed f64 — real fit labels vs sklearn (cpu; rocm
/// skips-with-log).
#[test]
fn labels_match_sklearn_precomputed_f64() {
    if skip_f64("labels_match_sklearn precomputed") {
        return;
    }
    run_precomputed_labels("f64", "labels_match_sklearn precomputed f64");
}

fn run_precomputed_labels(dtype_tag: &str, label: &str) {
    let name = format!("hdbscan_precomputed_{dtype_tag}_seed42.npz");
    let case = load_npz(fixture(&name)).unwrap_or_else(|e| panic!("load {name}: {e}"));
    let sklearn = labels_i64(&case, "labels");
    let n = sklearn.len();
    let dist: Vec<f64> = case.expect_f64("X").to_vec();
    assert_eq!(dist.len(), n * n, "precomputed X is the n×n distance matrix");

    let (got, _probs) = fit_precomputed(&dist, n, FitKnobs::defaults(HDB_BLOB_MCS));
    let acc = best_match_accuracy_pinned_noise(&got, &sklearn);
    assert!(
        (acc - 1.0).abs() < f64::EPSILON,
        "{label}: labels not a -1-pinned permutation of sklearn (acc={acc})\n got={got:?}\n exp={sklearn:?}"
    );
}

// ---------------------------------------------------------------------------
// HDBS-02 / D-04 TRUE GATE: the tie-heavy + duplicate-point fixture. Same
// pinned-noise exactness gate over an adversarial tie-heavy MST design, PLUS the
// duplicate row (R-9) must carry its partner's label.
// ---------------------------------------------------------------------------

/// The tie-heavy fixture geometry (2 features, mcs = HDB_TIE_MCS = 3).
const HDB_TIE_N_FEATURES: usize = 2;
const HDB_TIE_MCS: usize = 3;

/// `tie_break_exact` f32 — the D-04 TRUE GATE on the tie-heavy lattice + duplicate.
#[test]
fn tie_break_exact_f32() {
    let backend = capability::active_backend_name();
    capability::log_oracle_dtype(capability::FloatKind::F32, backend, "default");
    let case = load_npz(fixture("hdbscan_tieheavy_f32_seed42.npz")).expect("load tieheavy f32");
    run_tie_break(&case, "tie_break_exact f32");
}

/// `tie_break_exact` f64 — the D-04 TRUE GATE (cpu runs; rocm skips-with-log).
#[test]
fn tie_break_exact_f64() {
    if skip_f64("tie_break_exact") {
        return;
    }
    let case = load_npz(fixture("hdbscan_tieheavy_f64_seed42.npz")).expect("load tieheavy f64");
    run_tie_break(&case, "tie_break_exact f64");
}

fn run_tie_break(case: &OracleCase, label: &str) {
    let sklearn = labels_i64(case, "labels");
    let n = sklearn.len();
    let x: Vec<f64> = case.expect_f64("X").to_vec();
    let (got, _probs) = fit_euclidean_via_precomputed(
        &x,
        n,
        HDB_TIE_N_FEATURES,
        FitKnobs::defaults(HDB_TIE_MCS),
    );
    let acc = best_match_accuracy_pinned_noise(&got, &sklearn);
    assert!(
        (acc - 1.0).abs() < f64::EPSILON,
        "{label}: tie-heavy labels not a -1-pinned permutation of sklearn (acc={acc})"
    );

    // R-9: the duplicate row must share its partner's label (a genuine distance-0
    // duplicate, identical to the oracle).
    let dup_a = case.expect_f64("dup_row_a")[0] as usize;
    let dup_b = case.expect_f64("dup_row_b")[0] as usize;
    assert_eq!(
        got[dup_a], got[dup_b],
        "{label}: duplicate rows {dup_a}/{dup_b} must share a label (R-9)"
    );
}

// ---------------------------------------------------------------------------
// HDBS-01 / D-06: per-point `probabilities_` match sklearn ≤1e-5.
// ---------------------------------------------------------------------------

/// The euclidean blob fixture geometry (HDB_BLOB_N_FEATURES = 4, mcs = 5).
const HDB_BLOB_N_FEATURES: usize = 4;

/// `probabilities_match` f32 — per-point membership strength vs sklearn ≤1e-5.
/// Routes the euclidean feature fixture through the precomputed path (plan 15-04).
#[test]
fn probabilities_match_f32() {
    let backend = capability::active_backend_name();
    capability::log_oracle_dtype(capability::FloatKind::F32, backend, "default");
    let case = load_npz(fixture("hdbscan_euclidean_f32_seed42.npz")).expect("load euclidean f32");
    run_probabilities(&case, &F32_TOL, "probabilities_match f32");
}

/// `probabilities_match` f64 — per-point membership strength (cpu; rocm skips).
#[test]
fn probabilities_match_f64() {
    if skip_f64("probabilities_match") {
        return;
    }
    let case = load_npz(fixture("hdbscan_euclidean_f64_seed42.npz")).expect("load euclidean f64");
    run_probabilities(&case, &F64_TOL, "probabilities_match f64");
}

fn run_probabilities(case: &OracleCase, tol: &Tolerance, label: &str) {
    let probabilities = case.expect_f64("probabilities").to_vec();
    let n = probabilities.len();
    let x: Vec<f64> = case.expect_f64("X").to_vec();
    let (got_labels, got) = fit_euclidean_via_precomputed(
        &x,
        n,
        HDB_BLOB_N_FEATURES,
        FitKnobs::defaults(HDB_BLOB_MCS),
    );
    // Sanity: labels match too (probabilities only make sense under matched labels).
    let sklearn = labels_i64(case, "labels");
    let acc = best_match_accuracy_pinned_noise(&got_labels, &sklearn);
    assert!(
        (acc - 1.0).abs() < f64::EPSILON,
        "{label}: labels diverged before the probability compare (acc={acc})"
    );
    assert_close(&got, &probabilities, tol, label);
}

// ---------------------------------------------------------------------------
// HDBS-03 / D-07: GLOSH `outlier_scores_` match hdbscan 0.8.44 ≤1e-5.
// ---------------------------------------------------------------------------

/// `outlier_scores_match` f32 — GLOSH per-point scores vs hdbscan 0.8.44 ≤1e-5.
#[test]
fn outlier_scores_match_f32() {
    let backend = capability::active_backend_name();
    capability::log_oracle_dtype(capability::FloatKind::F32, backend, "default");
    let case = load_npz(fixture("hdbscan_euclidean_f32_seed42.npz")).expect("load euclidean f32");
    run_outlier_scores::<f32>(&case, &F32_TOL, "outlier_scores_match f32");
}

/// `outlier_scores_match` f64 — GLOSH per-point scores (cpu; rocm skips).
#[test]
fn outlier_scores_match_f64() {
    if skip_f64("outlier_scores_match") {
        return;
    }
    let case = load_npz(fixture("hdbscan_euclidean_f64_seed42.npz")).expect("load euclidean f64");
    run_outlier_scores::<f64>(&case, &F64_TOL, "outlier_scores_match f64");
}

/// Fit the euclidean blob fixture under the real device front-end (Euclidean,
/// Variant B) and assert the fitted GLOSH `outlier_scores_` match the committed
/// `hdbscan` 0.8.44 oracle array ≤1e-5 (HDBS-03 / D-07). The fixture's
/// `outlier_scores` were generated by the 0.8.44 cross-check fit, NOT sklearn
/// (which has no GLOSH); per-point compare needs no permutation (GLOSH is keyed by
/// point, not cluster). Monomorphised per dtype so the f32/f64 device path is
/// exercised exactly.
fn run_outlier_scores<F>(case: &OracleCase, tol: &Tolerance, label: &str)
where
    F: cubecl::prelude::Float + cubecl::prelude::CubeElement + bytemuck::Pod,
{
    let outlier_scores = case.expect_f64("outlier_scores").to_vec();
    let n = outlier_scores.len();
    let x: Vec<f64> = case.expect_f64("X").to_vec();
    let got = fit_outlier_scores::<F>(
        &x,
        n,
        HDB_BLOB_N_FEATURES,
        FitKnobs::defaults(HDB_BLOB_MCS),
    );
    assert_close(&got, &outlier_scores, tol, label);
}

// ---------------------------------------------------------------------------
// HDBS-04 / Pitfall 6: `centroids_`/`medoids_` match sklearn ≤1e-5 under the SAME
// label permutation (map each fitted cluster id to its sklearn id via the label
// confusion, then compare the centre rows).
// ---------------------------------------------------------------------------

/// `centers_match` f32 — `centroids_`/`medoids_` vs sklearn (same permutation).
#[test]
fn centers_match_f32() {
    let backend = capability::active_backend_name();
    capability::log_oracle_dtype(capability::FloatKind::F32, backend, "default");
    let case = load_npz(fixture("hdbscan_euclidean_f32_seed42.npz")).expect("load euclidean f32");
    run_centers::<f32>(&case, &F32_TOL, "centers_match f32");
}

/// `centers_match` f64 — `centroids_`/`medoids_` vs sklearn (cpu; rocm skips).
#[test]
fn centers_match_f64() {
    if skip_f64("centers_match") {
        return;
    }
    let case = load_npz(fixture("hdbscan_euclidean_f64_seed42.npz")).expect("load euclidean f64");
    run_centers::<f64>(&case, &F64_TOL, "centers_match f64");
}

/// Fit the euclidean blob fixture under the real device front-end with
/// `store_centers='both'` and return `(labels, centroids, medoids)` host-side
/// (HDBS-04, plan 15-06). `centroids`/`medoids` are row-major
/// `n_clusters × n_features`. Monomorphised per dtype.
fn fit_centers<F>(x: &[f64], n: usize, d: usize, mcs: usize) -> (Vec<i64>, Vec<f64>, Vec<f64>)
where
    F: cubecl::prelude::Float + cubecl::prelude::CubeElement + bytemuck::Pod,
{
    use mlrs_algos::cluster::hdbscan::StoreCenters;

    let client = runtime::active_client();
    let mut pool: BufferPool<ActiveRuntime> = BufferPool::new(client);
    let x_f: Vec<F> = x
        .iter()
        .map(|&v| match std::mem::size_of::<F>() {
            4 => *bytemuck::from_bytes::<F>(bytemuck::bytes_of(&(v as f32))),
            8 => *bytemuck::from_bytes::<F>(bytemuck::bytes_of(&v)),
            _ => unreachable!("f32/f64 only"),
        })
        .collect();
    let x_dev: DeviceArray<ActiveRuntime, F> = DeviceArray::from_host(&mut pool, &x_f);

    let fitted = Hdbscan::<F>::builder()
        .min_cluster_size(mcs)
        .metric(Metric::Euclidean)
        .store_centers(Some(StoreCenters::Both))
        .build::<F>()
        .expect("build euclidean store_centers")
        .fit(&mut pool, &x_dev, None, (n, d))
        .expect("euclidean fit");

    let labels: Vec<i64> = fitted.labels(&pool).iter().map(|&l| l as i64).collect();
    let to_f64 = |v: &[F]| -> Vec<f64> {
        v.iter()
            .map(|&x| match std::mem::size_of::<F>() {
                4 => *bytemuck::from_bytes::<f32>(bytemuck::bytes_of(&x)) as f64,
                8 => *bytemuck::from_bytes::<f64>(bytemuck::bytes_of(&x)),
                _ => unreachable!("f32/f64 only"),
            })
            .collect()
    };
    let centroids = to_f64(&fitted.centroids(&pool).expect("store_centers='both' produces centroids"));
    let medoids = to_f64(&fitted.medoids(&pool).expect("store_centers='both' produces medoids"));
    (labels, centroids, medoids)
}

fn run_centers<F>(case: &OracleCase, tol: &Tolerance, label: &str)
where
    F: cubecl::prelude::Float + cubecl::prelude::CubeElement + bytemuck::Pod,
{
    let sklearn = labels_i64(case, "labels");
    let centroids_ref = case.expect_f64("centroids");
    let medoids_ref = case.expect_f64("medoids");
    let n_features = 4usize; // euclidean fixture geometry (HDB_BLOB_N_FEATURES).
    let n_clusters = centroids_ref.len() / n_features;

    // Fit the real estimator with store_centers='both' (HDBS-04). Compare the
    // fitted centroids_/medoids_ to sklearn under the SAME label permutation
    // (Pitfall 6): `best_mapping` maps each fitted cluster id to its sklearn id via
    // the label confusion, then per-cluster `assert_close` checks the centre rows.
    let n = sklearn.len();
    let x: Vec<f64> = case.expect_f64("X").to_vec();
    let (got_labels, got_centroids, got_medoids) =
        fit_centers::<F>(&x, n, n_features, HDB_BLOB_MCS);

    let mapping = best_mapping(&got_labels, &sklearn);
    for fitted_c in 0..n_clusters {
        let ref_c = *mapping
            .get(&(fitted_c as i64))
            .unwrap_or_else(|| panic!("{label}: cluster {fitted_c} unmapped"))
            as usize;
        let cg = &got_centroids[fitted_c * n_features..(fitted_c + 1) * n_features];
        let ce = &centroids_ref[ref_c * n_features..(ref_c + 1) * n_features];
        assert_close(
            cg,
            ce,
            tol,
            &format!("{label} centroid[{fitted_c}->{ref_c}]"),
        );
        let mg = &got_medoids[fitted_c * n_features..(fitted_c + 1) * n_features];
        let me = &medoids_ref[ref_c * n_features..(ref_c + 1) * n_features];
        assert_close(mg, me, tol, &format!("{label} medoid[{fitted_c}->{ref_c}]"));
    }
}

/// HDBS-04 / T-15-06-V5: `store_centers` is FEATURE-ARRAY ONLY — requesting it with
/// `Metric::Precomputed` is a typed error (there are no feature rows to average),
/// matching sklearn. The fit must reject BEFORE producing garbage centers.
#[test]
fn store_centers_precomputed_errors() {
    use mlrs_algos::cluster::hdbscan::StoreCenters;
    use mlrs_algos::error::AlgoError;

    let client = runtime::active_client();
    let mut pool: BufferPool<ActiveRuntime> = BufferPool::new(client);

    // A small symmetric square distance matrix (precomputed path).
    let n = 4usize;
    let d: Vec<f64> = vec![
        0.0, 1.0, 5.0, 9.0, //
        1.0, 0.0, 2.0, 6.0, //
        5.0, 2.0, 0.0, 3.0, //
        9.0, 6.0, 3.0, 0.0, //
    ];
    let x_dev: DeviceArray<ActiveRuntime, f64> = DeviceArray::from_host(&mut pool, &d);

    let err = Hdbscan::<f64>::builder()
        .min_cluster_size(2)
        .metric(Metric::Precomputed)
        .store_centers(Some(StoreCenters::Both))
        .build::<f64>()
        .expect("build precomputed store_centers")
        .fit(&mut pool, &x_dev, None, (n, n))
        .err();

    assert!(
        matches!(err, Some(AlgoError::Unsupported { estimator: "hdbscan", .. })),
        "store_centers with Metric::Precomputed must be AlgoError::Unsupported, got {err:?}"
    );
}

// ---------------------------------------------------------------------------
// HDBS-01 / D-09: the nested-density fixture's non-default eom/leaf/epsilon/
// max_cluster_size/alpha label vectors are each an exact pinned-noise permutation
// of the corresponding oracle. (Epsilon is cross-oracled against hdbscan 0.8.44 —
// sklearn 1.9.0's epsilon_search crashes on merging trees; see gen_oracle.py.)
// ---------------------------------------------------------------------------

/// The nested-density fixture geometry (2 features, mcs = HDB_NESTED_MCS = 20).
const HDB_NESTED_N_FEATURES: usize = 2;
const HDB_NESTED_MCS: usize = 20;

/// `labels_alpha` is the FEATURE-path (Variant-B) alpha gate (Pitfall 2): the
/// oracle was generated on the feature matrix, whose `alpha` scaling differs from
/// the precomputed (Variant-A) path wired in 15-04 — sklearn itself partitions
/// differently (precomputed+α=0.5 → 2 clusters, feature+α=0.5 → 3). It is un-
/// ignored by plan 15-05 once the feature-metric `mst_from_data_matrix` (Variant
/// B) front-end lands. Kept here as an explicit, addressable marker so the D-09
/// alpha knob is not silently dropped.
#[test]
fn selection_knob_alpha_feature_path() {
    let backend = capability::active_backend_name();
    capability::log_oracle_dtype(capability::FloatKind::F64, backend, "alpha feature path");
    if skip_f64("selection_knob_alpha_feature_path") {
        return;
    }
    // The `labels_alpha` oracle was generated on the FEATURE path with `alpha=0.5`
    // (gen_oracle.py:1194, eom, nested euclidean design). The feature path's
    // Variant-B alpha placement (`pair_distance /= alpha`, RAW core) is what
    // reproduces this partition — so we fit the FEATURE `X` directly under
    // Euclidean (Variant B) with alpha=0.5, NOT the precomputed (Variant-A) path.
    let case = load_npz(fixture("hdbscan_nested_f64_seed42.npz")).expect("load nested f64");
    let x: Vec<f64> = case.expect_f64("X").to_vec();
    let oracle = labels_i64(&case, "labels_alpha");
    let n = oracle.len();
    let knobs = FitKnobs { alpha: 0.5, ..FitKnobs::defaults(HDB_NESTED_MCS) };
    let (got, _probs) =
        fit_feature_metric::<f64>(&x, n, HDB_NESTED_N_FEATURES, Metric::Euclidean, knobs);
    let acc = best_match_accuracy_pinned_noise(&got, &oracle);
    assert!(
        (acc - 1.0).abs() < f64::EPSILON,
        "selection_knob_alpha_feature_path: labels_alpha not a -1-pinned permutation of the feature-path oracle (acc={acc})\n got={got:?}\n exp={oracle:?}"
    );
}

/// `selection_knobs` f32 — each non-default knob's labels match its oracle.
#[test]
fn selection_knobs_f32() {
    let backend = capability::active_backend_name();
    capability::log_oracle_dtype(capability::FloatKind::F32, backend, "default");
    let case = load_npz(fixture("hdbscan_nested_f32_seed42.npz")).expect("load nested f32");
    run_selection_knobs(&case, "selection_knobs f32");
}

/// `selection_knobs` f64 — each non-default knob's labels (cpu; rocm skips).
#[test]
fn selection_knobs_f64() {
    if skip_f64("selection_knobs") {
        return;
    }
    let case = load_npz(fixture("hdbscan_nested_f64_seed42.npz")).expect("load nested f64");
    run_selection_knobs(&case, "selection_knobs f64");
}

fn run_selection_knobs(case: &OracleCase, label: &str) {
    let x: Vec<f64> = case.expect_f64("X").to_vec();
    let n = case.expect_f64("labels").len();
    let dist = euclidean_distance_matrix(&x, n, HDB_NESTED_N_FEATURES);

    // Each oracle knob → the matching builder configuration (gen_oracle.py:1182).
    // eom: default; leaf: method=Leaf; maxcluster: max_cluster_size=35;
    // epsilon: leaf + cluster_selection_epsilon=1.0 (the hdbscan-0.8.44 oracle).
    //
    // NOTE (Pitfall 2 / plan 15-05 scope): the `labels_alpha` oracle was generated
    // on the FEATURE path, whose alpha placement is `pair_distance /= alpha` with
    // RAW core distances (Variant B). The precomputed path used here divides the
    // WHOLE matrix by alpha BEFORE core distances (Variant A) — a genuinely
    // different reachability that sklearn ITSELF resolves to a different partition
    // (precomputed+alpha=0.5 → 2 clusters vs feature+alpha=0.5 → 3). So the alpha
    // knob is the FEATURE-path (Variant B) gate owned by plan 15-05; here we
    // exercise every knob the precomputed path can reproduce exactly (alpha=1.0).
    let mcs = HDB_NESTED_MCS;
    let configs: [(&str, FitKnobs); 4] = [
        ("labels_eom", FitKnobs::defaults(mcs)),
        (
            "labels_leaf",
            FitKnobs { method: ClusterSelectionMethod::Leaf, ..FitKnobs::defaults(mcs) },
        ),
        (
            "labels_maxcluster",
            FitKnobs { max_cluster_size: 35, ..FitKnobs::defaults(mcs) },
        ),
        (
            "labels_epsilon",
            FitKnobs {
                method: ClusterSelectionMethod::Leaf,
                epsilon: 1.0,
                ..FitKnobs::defaults(mcs)
            },
        ),
    ];

    for (knob, knobs) in configs {
        let oracle = labels_i64(case, knob);
        let (got, _probs) = fit_precomputed(&dist, n, knobs);
        let acc = best_match_accuracy_pinned_noise(&got, &oracle);
        assert!(
            (acc - 1.0).abs() < f64::EPSILON,
            "{label} [{knob}]: labels not a -1-pinned permutation of the oracle (acc={acc})\n got={got:?}\n exp={oracle:?}"
        );
    }
}

// ---------------------------------------------------------------------------
// HDBS-01 / D-08: data-independent build validation — bad hyperparameters are
// rejected at `build()` with a typed `BuildError`, BEFORE any data is seen.
// (Extends the kept Phase-12 `build_rejects_bad_min_cluster_size`.) This gate
// RUNS now — the build path already exists on the shell.
// ---------------------------------------------------------------------------

/// BLDR-01: `Hdbscan::new()` equals `Hdbscan::builder().build()?` on the
/// hyperparameter subset (single-source defaults). Pure host comparison. KEPT
/// verbatim from the Phase-12 shell.
#[test]
fn defaults_equal() {
    let from_new = Hdbscan::<f64>::new();
    let from_builder = Hdbscan::<f64>::builder()
        .build::<f64>()
        .expect("default HdbscanBuilder builds");
    assert!(
        from_new.hyperparams_eq(&from_builder),
        "Hdbscan::new() and builder().build()? must agree on hyperparameters (BLDR-01)"
    );
}

/// D-08 build validation (HDBS-01): a `min_cluster_size < 2` is rejected at
/// `build()` with the typed `BuildError::InvalidMinClusterSize`, BEFORE any data.
/// (Extends the Phase-12 `build_rejects_bad_min_cluster_size`; 15-NN adds the
/// `min_samples`/`max_cluster_size`/`alpha`/minkowski-`p` cases as those typed
/// `BuildError` variants land.)
#[test]
fn build_validation() {
    let bad = Hdbscan::<f64>::builder()
        .min_cluster_size(1)
        .build::<f64>()
        .err();
    assert!(
        matches!(
            bad,
            Some(BuildError::InvalidMinClusterSize { min_cluster_size, .. })
                if min_cluster_size == 1
        ),
        "min_cluster_size < 2 must be BuildError::InvalidMinClusterSize, got {bad:?}"
    );

    // min_samples = Some(0) is rejected; Some(1) is accepted (15-03 / D-09).
    let bad_ms = Hdbscan::<f64>::builder()
        .min_samples(Some(0))
        .build::<f64>()
        .err();
    assert!(
        matches!(
            bad_ms,
            Some(BuildError::InvalidMinSamples { min_samples, .. }) if min_samples == 0
        ),
        "min_samples = Some(0) must be BuildError::InvalidMinSamples, got {bad_ms:?}"
    );
    assert!(
        Hdbscan::<f64>::builder()
            .min_samples(Some(1))
            .build::<f64>()
            .is_ok(),
        "min_samples = Some(1) must be accepted"
    );

    // max_cluster_size = 3 with min_cluster_size = 5 is rejected (neither 0 nor
    // >= mcs); 0 (unbounded) and 5 (== mcs) are accepted.
    let bad_mxc = Hdbscan::<f64>::builder()
        .min_cluster_size(5)
        .max_cluster_size(3)
        .build::<f64>()
        .err();
    assert!(
        matches!(
            bad_mxc,
            Some(BuildError::InvalidMaxClusterSize { max_cluster_size, min_cluster_size, .. })
                if max_cluster_size == 3 && min_cluster_size == 5
        ),
        "max_cluster_size below min_cluster_size must be InvalidMaxClusterSize, got {bad_mxc:?}"
    );
    assert!(
        Hdbscan::<f64>::builder()
            .min_cluster_size(5)
            .max_cluster_size(0)
            .build::<f64>()
            .is_ok(),
        "max_cluster_size = 0 (unbounded) must be accepted"
    );
    assert!(
        Hdbscan::<f64>::builder()
            .min_cluster_size(5)
            .max_cluster_size(5)
            .build::<f64>()
            .is_ok(),
        "max_cluster_size == min_cluster_size must be accepted"
    );

    // alpha <= 0 is rejected; alpha = 1.0 is accepted.
    let bad_alpha = Hdbscan::<f64>::builder().alpha(0.0).build::<f64>().err();
    assert!(
        matches!(
            bad_alpha,
            Some(BuildError::InvalidAlphaHdbscan { alpha, .. }) if alpha == 0.0
        ),
        "alpha = 0.0 must be BuildError::InvalidAlphaHdbscan, got {bad_alpha:?}"
    );
    assert!(
        Hdbscan::<f64>::builder().alpha(-1.0).build::<f64>().is_err(),
        "negative alpha must be rejected"
    );
    assert!(
        Hdbscan::<f64>::builder().alpha(1.0).build::<f64>().is_ok(),
        "alpha = 1.0 must be accepted"
    );

    // Metric::Minkowski { p < 1 } is rejected; p = 2.0 accepted; Precomputed
    // round-trips through the builder.
    let bad_p = Hdbscan::<f64>::builder()
        .metric(Metric::Minkowski { p: 0.5 })
        .build::<f64>()
        .err();
    assert!(
        matches!(
            bad_p,
            Some(BuildError::InvalidMinkowskiP { p, .. }) if p == 0.5
        ),
        "minkowski p < 1 must be BuildError::InvalidMinkowskiP, got {bad_p:?}"
    );
    assert!(
        Hdbscan::<f64>::builder()
            .metric(Metric::Minkowski { p: 2.0 })
            .build::<f64>()
            .is_ok(),
        "minkowski p = 2.0 must be accepted"
    );
    assert!(
        Hdbscan::<f64>::builder()
            .metric(Metric::Precomputed)
            .build::<f64>()
            .is_ok(),
        "Metric::Precomputed must construct"
    );
}

// ---------------------------------------------------------------------------
// HDBS-01 / T-15-OVF: the device front-end must not leak across re-fits, and must
// keep `peak_bytes` sub-quadratic (no full `n×n` resident — query-axis-tiled).
//
// As of plan 15-05 the device front-end is wired (Euclidean default = the
// source-tracking Variant-B path, which never materialises an `n×n` device block).
// The gate now asserts BOTH (1) re-construct + re-fit does not grow `live_bytes`
// AND (2) the peak device residency stays strictly below a full `n×n` f64 matrix
// (the Variant-B no-`n×n` guarantee; the KNN prim is query-axis tiled so its peak
// is `O(tile·n + n·k)`, not `O(n²)`).
// ---------------------------------------------------------------------------

/// `memory_gate` — re-CONSTRUCT + re-fit at the same shape does not grow
/// `live_bytes` AND the device front-end's `peak_bytes` stays sub-quadratic (no
/// full `n×n` resident for the Variant-B feature path). The consuming `fit(self)`
/// forces reconstruction each iteration.
#[test]
fn memory_gate() {
    use mlrs_algos::typestate::Fit;
    use mlrs_backend::device_array::DeviceArray;
    use mlrs_backend::pool::BufferPool;
    use mlrs_backend::runtime::{self, ActiveRuntime};

    if skip_f64("memory_gate") {
        return;
    }

    let client = runtime::active_client();
    let mut pool: BufferPool<ActiveRuntime> = BufferPool::new(client);

    // A non-trivial n so the sub-quadratic bound is meaningful: a full n×n f64
    // block would be n*n*8 bytes; the Variant-B path must peak well below it.
    let n = 64usize;
    let p = 4usize;
    let x_host: Vec<f64> = (0..n * p).map(|i| (i % 17) as f64 * 0.5).collect();
    let x_dev: DeviceArray<ActiveRuntime, f64> = DeviceArray::from_host(&mut pool, &x_host);

    let fitted = Hdbscan::<f64>::new()
        .fit(&mut pool, &x_dev, None, (n, p))
        .expect("first fit");
    drop(fitted);
    let live_after_first = pool.stats().live_bytes;

    // (2) Sub-quadratic peak: the Variant-B feature path never builds a full n×n
    // device block. The KNN prim is query-axis tiled (peak O(tile·n + n·k)); assert
    // the observed high-water mark is strictly below a full n×n f64 matrix.
    let nn_bytes = (n as u64) * (n as u64) * (std::mem::size_of::<f64>() as u64);
    let peak = pool.stats().peak_bytes;
    assert!(
        peak < nn_bytes,
        "device front-end peak_bytes {peak} must stay below a full n×n f64 block {nn_bytes} (no n×n resident; Variant B)"
    );

    const REFITS: usize = 4;
    for k in 0..REFITS {
        let fitted = Hdbscan::<f64>::new()
            .fit(&mut pool, &x_dev, None, (n, p))
            .expect("re-fit");
        drop(fitted);
        let live = pool.stats().live_bytes;
        assert!(
            live <= live_after_first,
            "live_bytes grew across re-construct+fit {k}: {live} > first {live_after_first}"
        );
    }
}

// ---------------------------------------------------------------------------
// HDBS-01: edge cases — all-noise / single-cluster / n<min_cluster_size match
// sklearn. Pinned-noise exact gate over the degenerate fixtures.
// ---------------------------------------------------------------------------

/// `edge_cases` f32 — all-noise / single-cluster / tiny fixtures match sklearn.
#[test]
fn edge_cases_f32() {
    let backend = capability::active_backend_name();
    capability::log_oracle_dtype(capability::FloatKind::F32, backend, "default");
    run_edge_cases("f32", "edge_cases f32");
}

/// `edge_cases` f64 — degenerate fixtures match sklearn (cpu; rocm skips).
#[test]
fn edge_cases_f64() {
    if skip_f64("edge_cases") {
        return;
    }
    run_edge_cases("f64", "edge_cases f64");
}

fn run_edge_cases(dtype_tag: &str, label: &str) {
    // The edge fixtures all use HDB_MIN_CLUSTER_SIZE = 5 features-of-3 designs, with
    // per-structure overrides matching gen_oracle.py:1124-1132:
    //   - allnoise: defaults (eom) → every point is noise.
    //   - single:   allow_single_cluster=True + min_samples=2 (a homogeneous blob
    //               has no density split; eom selects the root as the one cluster).
    //   - tiny:     min_samples=1 (n < mcs would over-flag; sklearn yields all-noise).
    let edge_mcs = 5usize;
    let n_features = 3usize;
    let cases: [(&str, FitKnobs); 3] = [
        ("allnoise", FitKnobs::defaults(edge_mcs)),
        (
            "single",
            FitKnobs {
                min_samples: Some(2),
                allow_single_cluster: true,
                ..FitKnobs::defaults(edge_mcs)
            },
        ),
        (
            "tiny",
            FitKnobs { min_samples: Some(1), ..FitKnobs::defaults(edge_mcs) },
        ),
    ];

    for (structure, knobs) in cases {
        let name = format!("hdbscan_{structure}_{dtype_tag}_seed42.npz");
        let case = load_npz(fixture(&name)).unwrap_or_else(|e| panic!("load {name}: {e}"));
        let sklearn = labels_i64(&case, "labels");
        let n = sklearn.len();
        let x: Vec<f64> = case.expect_f64("X").to_vec();
        let (got, _probs) = fit_euclidean_via_precomputed(&x, n, n_features, knobs);
        let acc = best_match_accuracy_pinned_noise(&got, &sklearn);
        assert!(
            (acc - 1.0).abs() < f64::EPSILON,
            "{label} [{structure}]: labels not a -1-pinned permutation of sklearn (acc={acc})\n got={got:?}\n exp={sklearn:?}"
        );
    }
}

// ---------------------------------------------------------------------------
// HDBS-02 / plan 15-03: the MST + single-linkage host back-end. The full
// fit-vs-oracle label gate runs in 15-04 (condense/select) + 15-05 (device
// front-end); here we characterize the two oracle Prim variants + the UnionFind
// single-linkage DIRECTLY on hand-built DISTINCT-weight inputs (RESEARCH
// Pitfall 1 option 2 — distinct weights make the sort tie-free and the hierarchy
// deterministic). These assert VALUES (not just non-panic), per R-9.
// ---------------------------------------------------------------------------

use mlrs_algos::cluster::hdbscan::mst::{
    argsort_by_weight, core_distances_dense, mst_from_data_matrix, mst_from_mutual_reachability,
    mutual_reachability_dense,
};
use mlrs_algos::cluster::hdbscan::single_linkage::{make_single_linkage, SingleLinkageEdge, UnionFind};

use mlrs_algos::cluster::hdbscan::condense::{condense_tree, CondensedNode};
use mlrs_algos::cluster::hdbscan::stability::{compute_stability, max_lambdas};

/// A balanced two-cluster single-linkage hierarchy over `n=8` points used by the
/// condense/stability characterization gates (plan 15-04). Two clusters
/// `{0,1,2,3}` and `{4,5,6,7}` each merge tightly (d=1,1.5,2) then join at the
/// top (d=10). The internal node ids follow the `N+i` convention so the BFS root
/// is `2*(N-1) = 14`. Ground truth taken from sklearn `_condense_tree` /
/// `tree_to_labels` (verbatim oracle).
fn hand_hierarchy_n8() -> Vec<SingleLinkageEdge> {
    let mk = |left, right, distance, size| SingleLinkageEdge {
        left,
        right,
        distance,
        size,
    };
    vec![
        mk(0, 1, 1.0, 2),  // node 8
        mk(8, 2, 1.5, 3),  // node 9
        mk(9, 3, 2.0, 4),  // node 10  -> cluster {0,1,2,3}
        mk(4, 5, 1.0, 2),  // node 11
        mk(11, 6, 1.5, 3), // node 12
        mk(12, 7, 2.0, 4), // node 13  -> cluster {4,5,6,7}
        mk(10, 13, 10.0, 8), // node 14 -> top
    ]
}

/// HDBS-02 / Pattern 5: `condense_tree` runt-prunes the single-linkage hierarchy
/// by `min_cluster_size` (NOT `min_samples`), producing the sklearn condensed
/// tree exactly. At `mcs=2` the top split keeps both 4-point children (relabeled
/// 9 and 10 from root 8) at `lambda = 1/10 = 0.1`, then each sub-cluster sheds its
/// points as runts. Ground truth from sklearn `_condense_tree(H, 2)`.
#[test]
fn condense_tree_runt_prunes_by_min_cluster_size() {
    let h = hand_hierarchy_n8();
    let ct = condense_tree(&h, 2);

    let expect = vec![
        CondensedNode { parent: 8, child: 9, lambda: 0.1, cluster_size: 4 },
        CondensedNode { parent: 8, child: 10, lambda: 0.1, cluster_size: 4 },
        CondensedNode { parent: 9, child: 3, lambda: 0.5, cluster_size: 1 },
        CondensedNode { parent: 10, child: 7, lambda: 0.5, cluster_size: 1 },
        CondensedNode { parent: 9, child: 2, lambda: 2.0 / 3.0, cluster_size: 1 },
        CondensedNode { parent: 10, child: 6, lambda: 2.0 / 3.0, cluster_size: 1 },
        CondensedNode { parent: 9, child: 0, lambda: 1.0, cluster_size: 1 },
        CondensedNode { parent: 9, child: 1, lambda: 1.0, cluster_size: 1 },
        CondensedNode { parent: 10, child: 4, lambda: 1.0, cluster_size: 1 },
        CondensedNode { parent: 10, child: 5, lambda: 1.0, cluster_size: 1 },
    ];
    assert_eq!(ct, expect, "mcs=2 condensed tree must match sklearn _condense_tree");

    // mcs=4: the sub-clusters (size 3 after the first runt drop) fall below 4, so
    // ONLY the top split survives; all 8 points fall out under 9 / 10 at lambda
    // 1/2 = 0.5. Ground truth from sklearn _condense_tree(H, 4).
    let ct4 = condense_tree(&h, 4);
    let parents4: Vec<usize> = ct4.iter().map(|r| r.parent).collect();
    assert_eq!(parents4[0..2], [8, 8], "mcs=4 keeps the top split (root children 9,10)");
    // All point children fall out at lambda 0.5 under 9 / 10.
    for r in &ct4[2..] {
        assert!(r.child < 8, "mcs=4 sheds singleton points");
        assert!((r.lambda - 0.5).abs() < 1e-12, "mcs=4 points fall out at 1/2=0.5");
        assert_eq!(r.cluster_size, 1);
    }
}

/// HDBS-02 / Pattern 5: a distance-0 merge yields `lambda = INFTY` (the runt
/// fall-out branch). A 3-point hierarchy where the final merge has distance 0.
#[test]
fn condense_tree_infty_on_zero_distance() {
    let mk = |left, right, distance, size| SingleLinkageEdge { left, right, distance, size };
    // n=3: node3=(0,1,d=0,size2); node4=(3,2,d=1,size3). Root = 2*(3-1) = 4.
    let h = vec![mk(0, 1, 0.0, 2), mk(3, 2, 1.0, 3)];
    let ct = condense_tree(&h, 2);
    // The d=0 merge produces lambda=INFTY for whichever rows carry it.
    assert!(
        ct.iter().any(|r| r.lambda.is_infinite()),
        "a distance-0 merge must produce a lambda=INFTY condensed row"
    );
}

/// HDBS-02 / Pattern 6: `compute_stability` accumulates
/// `(lambda - births[parent]) * cluster_size` per parent, with `births[root]=0`.
/// Ground truth from sklearn (`_compute_stability` semantics): mcs=2 →
/// `{8: 0.8, 9: 2.766667, 10: 2.766667}`, mcs=4 → `{8: 0.8, 9: 1.6, 10: 1.6}`.
#[test]
fn compute_stability_matches_sklearn() {
    let h = hand_hierarchy_n8();

    let s2 = compute_stability(&condense_tree(&h, 2));
    assert!((s2[&8] - 0.8).abs() < 1e-9, "stability[8] mcs=2: {}", s2[&8]);
    assert!((s2[&9] - 2.766666666).abs() < 1e-6, "stability[9] mcs=2: {}", s2[&9]);
    assert!((s2[&10] - 2.766666666).abs() < 1e-6, "stability[10] mcs=2: {}", s2[&10]);

    let s4 = compute_stability(&condense_tree(&h, 4));
    assert!((s4[&8] - 0.8).abs() < 1e-9, "stability[8] mcs=4: {}", s4[&8]);
    assert!((s4[&9] - 1.6).abs() < 1e-9, "stability[9] mcs=4: {}", s4[&9]);
    assert!((s4[&10] - 1.6).abs() < 1e-9, "stability[10] mcs=4: {}", s4[&10]);
}

/// HDBS-02 / Pattern 6: `max_lambdas` returns the per-parent maximum lambda
/// ("death" lambda). On the mcs=2 condensed tree the max lambda under parents 9
/// and 10 is `1.0` (their points' final fall-out); parent 8's max is `0.1`.
#[test]
fn max_lambdas_per_parent() {
    let h = hand_hierarchy_n8();
    let ct = condense_tree(&h, 2);
    let deaths = max_lambdas(&ct);
    assert!((deaths[8] - 0.1).abs() < 1e-12, "deaths[8]: {}", deaths[8]);
    assert!((deaths[9] - 1.0).abs() < 1e-12, "deaths[9]: {}", deaths[9]);
    assert!((deaths[10] - 1.0).abs() < 1e-12, "deaths[10]: {}", deaths[10]);
}

/// Variant A (`mst_from_mutual_reachability`) recovers the expected spanning tree
/// on a small dense path-graph distance matrix with DISTINCT weights, and the
/// FIRST-min `argmin` tie-break is exercised. 4-point path 0-1-2-3 with edge
/// weights 1, 2, 3 along the path and larger off-path distances → the MST is the
/// path itself.
#[test]
fn mst_variant_a_distinct_weights() {
    let n = 4;
    // Symmetric distance matrix: path 0-1 (1.0), 1-2 (2.0), 2-3 (3.0); off-path
    // distances strictly larger so the unique MST is the path.
    let d = vec![
        0.0, 1.0, 5.0, 9.0, //
        1.0, 0.0, 2.0, 6.0, //
        5.0, 2.0, 0.0, 3.0, //
        9.0, 6.0, 3.0, 0.0, //
    ];
    // min_samples=1 → core distance = 0th smallest = the self-zero, so MR == d.
    let core = core_distances_dense(&d, n, 1);
    assert_eq!(core, vec![0.0, 0.0, 0.0, 0.0], "core dist with ms=1 is the self-zero");
    let mr = mutual_reachability_dense(&d, &core, n);
    assert_eq!(mr, d, "MR with zero core distances equals the distance matrix");

    let mst = mst_from_mutual_reachability(&mr, n);
    assert_eq!(mst.len(), n - 1, "an MST over n points has n-1 edges");
    // Edge set (unordered endpoints) must be {0-1, 1-2, 2-3} with weights 1,2,3.
    let mut weights: Vec<f64> = mst.iter().map(|&(_, _, w)| w).collect();
    weights.sort_by(|a, b| a.total_cmp(b));
    assert_eq!(weights, vec![1.0, 2.0, 3.0], "MST weights are the path edges");
}

/// Variant B (`mst_from_data_matrix`) on the SAME path graph via a closure that
/// returns the raw pairwise distance: with `alpha=1.0` and zero core distances it
/// recovers the identical path MST, and the strict-`<` lowest-`j` tie logic is
/// exercised (no panic, deterministic).
#[test]
fn mst_variant_b_matches_path() {
    let n = 4;
    let d = vec![
        0.0, 1.0, 5.0, 9.0, //
        1.0, 0.0, 2.0, 6.0, //
        5.0, 2.0, 0.0, 3.0, //
        9.0, 6.0, 3.0, 0.0, //
    ];
    let core = vec![0.0; n]; // raw core distances (Variant-B placement)
    let mst = mst_from_data_matrix(&core, n, 1.0, |i, j| d[i * n + j]);
    assert_eq!(mst.len(), n - 1);
    let mut weights: Vec<f64> = mst.iter().map(|&(_, _, w)| w).collect();
    weights.sort_by(|a, b| a.total_cmp(b));
    assert_eq!(weights, vec![1.0, 2.0, 3.0], "Variant B recovers the path MST");
}

/// The Variant-B alpha placement divides the PAIRWISE distance (not the core) by
/// alpha: with alpha=2 and zero core, every MST weight halves.
#[test]
fn mst_variant_b_alpha_divides_pairwise() {
    let n = 3;
    let d = vec![
        0.0, 2.0, 8.0, //
        2.0, 0.0, 4.0, //
        8.0, 4.0, 0.0, //
    ];
    let core = vec![0.0; n];
    let mst = mst_from_data_matrix(&core, n, 2.0, |i, j| d[i * n + j]);
    let mut weights: Vec<f64> = mst.iter().map(|&(_, _, w)| w).collect();
    weights.sort_by(|a, b| a.total_cmp(b));
    // raw path edges 2 and 4, divided by alpha=2 → 1 and 2.
    assert_eq!(weights, vec![1.0, 2.0], "alpha divides the pairwise distance (Variant B)");
}

/// `make_single_linkage` relabels `N+i` per merge and accumulates sizes. On the
/// distinct-weight path MST the hierarchy is deterministic: 3 merges, sizes
/// 2,3,4, fresh labels 4,5,6.
#[test]
fn single_linkage_relabels_and_accumulates() {
    let n = 4;
    // Argsorted path MST: (0,1,1), (1,2,2), (2,3,3).
    let edges = vec![(0usize, 1usize, 1.0f64), (1, 2, 2.0), (2, 3, 3.0)];
    let sorted = argsort_by_weight(&edges);
    assert_eq!(sorted, edges, "distinct ascending weights are already sorted");

    let sl = make_single_linkage(&sorted, n);
    assert_eq!(sl.len(), n - 1);
    // First merge: find(0)=0, find(1)=1 → new label 4, size 2.
    assert_eq!((sl[0].left, sl[0].right, sl[0].size), (0, 1, 2));
    assert_eq!(sl[0].distance, 1.0);
    // Second merge: find(1)=4 (compressed), find(2)=2 → label 5, size 3.
    assert_eq!((sl[1].left, sl[1].right, sl[1].size), (4, 2, 3));
    // Third merge: find(2)=5, find(3)=3 → label 6, size 4.
    assert_eq!((sl[2].left, sl[2].right, sl[2].size), (5, 3, 4));
}

/// The UnionFind `fast_find` path-compresses and `union` mints fresh labels —
/// the load-bearing single-linkage invariant.
#[test]
fn union_find_fresh_labels() {
    let mut uf = UnionFind::new(3); // labels 0,1,2 singletons; internal 3,4
    assert_eq!(uf.fast_find(0), 0);
    uf.union(0, 1); // mint label 3, size 2
    assert_eq!(uf.size_of(3), 2);
    assert_eq!(uf.fast_find(0), 3, "0 now roots at fresh label 3");
    assert_eq!(uf.fast_find(1), 3);
    uf.union(3, 2); // mint label 4, size 3
    assert_eq!(uf.size_of(4), 3);
    assert_eq!(uf.fast_find(2), 4);
    assert_eq!(uf.fast_find(0), 4, "path-compressed to the new root 4");
}

/// The precomputed `fit` path runs the full host MST → single-linkage pipeline
/// and stores the hierarchy on the estimator (plan 15-03). Validates squareness
/// rejection AND that a valid square matrix yields an `n-1`-edge hierarchy.
#[test]
fn precomputed_fit_builds_single_linkage() {
    use mlrs_algos::cluster::hdbscan::Metric;
    use mlrs_algos::typestate::Fit;
    use mlrs_backend::device_array::DeviceArray;
    use mlrs_backend::pool::BufferPool;
    use mlrs_backend::runtime::{self, ActiveRuntime};

    if skip_f64("precomputed_fit") {
        return;
    }

    let client = runtime::active_client();
    let mut pool: BufferPool<ActiveRuntime> = BufferPool::new(client);

    let n = 4usize;
    // A symmetric square distance matrix (path graph, distinct weights).
    let d: Vec<f64> = vec![
        0.0, 1.0, 5.0, 9.0, //
        1.0, 0.0, 2.0, 6.0, //
        5.0, 2.0, 0.0, 3.0, //
        9.0, 6.0, 3.0, 0.0, //
    ];
    let x_dev: DeviceArray<ActiveRuntime, f64> = DeviceArray::from_host(&mut pool, &d);

    let fitted = Hdbscan::<f64>::builder()
        .min_cluster_size(2)
        .metric(Metric::Precomputed)
        .build::<f64>()
        .expect("build precomputed")
        .fit(&mut pool, &x_dev, None, (n, n))
        .expect("precomputed fit");

    let sl = fitted
        .single_linkage()
        .expect("precomputed fit stores the single-linkage hierarchy");
    assert_eq!(sl.len(), n - 1, "hierarchy has n-1 merge rows");
    // The top merge spans all 4 points.
    assert_eq!(sl[n - 2].size, n, "final merge unites all points");

    // Squareness rejection (T-15-03-V5a): a non-square (n, p!=n) shape errors
    // before any host read.
    let bad = Hdbscan::<f64>::builder()
        .min_cluster_size(2)
        .metric(Metric::Precomputed)
        .build::<f64>()
        .expect("build")
        .fit(&mut pool, &x_dev, None, (2, 8));
    assert!(bad.is_err(), "non-square precomputed matrix must be rejected");
}

/// HDBS-01: `Hdbscan::fit_predict` is a faithful thin wrapper — it returns
/// exactly the labels that `Fit::fit` followed by `Hdbscan::<F, Fitted>::labels`
/// would. We do NOT re-gate oracle correctness here (the 39-test suite already
/// does that exhaustively); this only proves the convenience method is behaviorally
/// equivalent to the construct-then-fit-then-read path. Self-contained: a tiny
/// in-memory two-cluster Euclidean blob, no fixture loaded.
#[test]
fn fit_predict_matches_fit_then_labels() {
    if skip_f64("fit_predict_matches_fit_then_labels") {
        return;
    }

    let client = runtime::active_client();
    let mut pool: BufferPool<ActiveRuntime> = BufferPool::new(client);

    // Two visually separable clusters: 8 rows near the origin, 8 rows near (10,10),
    // 2 features. (i / 8) flips the cluster; cheap and deterministic.
    let n = 16usize;
    let p = 2usize;
    let mut x_host: Vec<f64> = Vec::with_capacity(n * p);
    for i in 0..n {
        let base = if i < 8 { 0.0 } else { 10.0 };
        let jitter = (i % 8) as f64 * 0.1;
        x_host.push(base + jitter);
        x_host.push(base + jitter);
    }
    let x_dev: DeviceArray<ActiveRuntime, f64> = DeviceArray::from_host(&mut pool, &x_host);

    // REFERENCE path: fit, then read labels off the Fitted estimator.
    let reference = Hdbscan::<f64>::new();
    let fitted = Fit::fit(reference, &mut pool, &x_dev, None, (n, p))
        .expect("reference fit succeeds on the cpu f64 gate");
    let expected: Vec<i32> = fitted.labels(&pool);

    // SUBJECT path: a SECOND identical estimator (both fit/fit_predict move self),
    // fit_predict returns a device i32 buffer of the same labels.
    let subject = Hdbscan::<f64>::new();
    let labels_dev = subject
        .fit_predict(&mut pool, &x_dev, (n, p))
        .expect("fit_predict succeeds on the cpu f64 gate");
    let actual: Vec<i32> = labels_dev.to_host(&pool);

    assert_eq!(
        actual, expected,
        "fit_predict must return exactly the labels fit-then-labels() would (noise = -1)"
    );
}
