//! Plan 15-02 Wave-0 — HDBSCAN (HDBS-01..04) oracle gate suite.
//!
//! This REPLACES the Phase-12 shell convention tests with the full Nyquist gate
//! suite each later HDBSCAN wave turns green. Every gate loads a committed
//! `hdbscan_*.npz` oracle fixture (generated by `scripts/gen_oracle.py` against
//! `sklearn.cluster.HDBSCAN` 1.9.0 + `hdbscan` 0.8.44 — see that file for the
//! design rationale; no Python at test time) and asserts the fitted estimator vs
//! the oracle:
//!
//!   - `labels_match_sklearn` — per metric × {f32,f64}, fitted `labels_` is a
//!     `-1`-PINNED permutation of sklearn's (`best_match_accuracy_pinned_noise
//!     == 1.0`, HDBS-02 / D-03).
//!   - `tie_break_exact` — the tie-heavy + duplicate-point fixture (D-04 TRUE
//!     GATE): same pinned-noise gate over an adversarial tie-heavy MST design,
//!     and the duplicate row (R-9) must share its partner's label.
//!   - `probabilities_match` — per-point `probabilities_` vs sklearn ≤1e-5
//!     (HDBS-01 / D-06).
//!   - `outlier_scores_match` — per-point GLOSH `outlier_scores_` vs hdbscan
//!     0.8.44 ≤1e-5 (HDBS-03 / D-07).
//!   - `centers_match` — `centroids_`/`medoids_` vs sklearn ≤1e-5 under the SAME
//!     label permutation (HDBS-04 / Pitfall 6).
//!   - `selection_knobs` — the nested-density fixture's non-default eom/leaf/
//!     epsilon/max_cluster_size/alpha label vectors are each an exact pinned-noise
//!     permutation of the corresponding oracle (HDBS-01 / D-09).
//!   - `build_validation` — `min_cluster_size`/`min_samples`/`max_cluster_size`/
//!     `alpha`/minkowski-`p` are rejected at build (data-independent, D-08).
//!   - `memory_gate` — re-construct + re-fit does not grow `live_bytes`, and the
//!     device front-end keeps `peak_bytes` sub-quadratic (no `n×n` resident).
//!   - `edge_cases` — all-noise / single-cluster / n<min_cluster_size match
//!     sklearn.
//!
//! WAVE-0 STATUS: the back-end algorithm is NOT built yet — the shell `fit` is
//! still trivial and the extended `Metric`, score/center accessors, and
//! non-Euclidean metrics do not exist. Gates that depend on those symbols are
//! `#[ignore]`d with a `// un-ignore in 15-NN` marker; their bodies are written
//! to COMPILE against the current shell (they load the fixture and exercise the
//! pinned-noise matcher / `assert_close` helper on the oracle arrays as a
//! self-consistency placeholder) so the file compiles green in Wave 0. The later
//! waves replace each placeholder body with the real fit-vs-oracle comparison and
//! drop the `#[ignore]`. `build_validation` runs NOW (the build path exists).
//!
//! f64 cases carry the `skip_f64_with_log` capability gate verbatim (cpu runs
//! f64; rocm skips per the CubeCL-HIP F64 gap). Per AGENTS.md §2 tests live in
//! `crates/mlrs-algos/tests/`, never an in-source `#[cfg(test)] mod tests`.

use std::path::PathBuf;

use mlrs_algos::cluster::hdbscan::{Hdbscan, Metric};
use mlrs_algos::error::BuildError;
use mlrs_backend::capability;
use mlrs_core::{
    best_mapping, best_match_accuracy_pinned_noise, load_npz, OracleCase, Tolerance, F32_TOL,
    F64_TOL,
};

// ---------------------------------------------------------------------------
// Fixture loader + cast/compare helpers (copied verbatim from kmeans_test.rs so
// the oracle plumbing is identical across estimators).
// ---------------------------------------------------------------------------

/// Resolve `<workspace_root>/tests/fixtures/<name>` (the committed-blob dir).
fn fixture(name: &str) -> PathBuf {
    let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let workspace_root = manifest
        .parent()
        .and_then(|p| p.parent())
        .expect("workspace root is two levels above the crate manifest dir");
    workspace_root.join("tests").join("fixtures").join(name)
}

/// numpy-`allclose` element compare: pass if `|got − exp| ≤ atol + rtol·|exp|`
/// (abs-OR-rel), the strict 1e-5 ABSOLUTE arm never loosened.
fn assert_close(got: &[f64], expected: &[f64], tol: &Tolerance, what: &str) {
    assert_eq!(
        got.len(),
        expected.len(),
        "{what}: length mismatch got={} expected={}",
        got.len(),
        expected.len()
    );
    for (i, (&g, &e)) in got.iter().zip(expected.iter()).enumerate() {
        let abs_err = (g - e).abs();
        let allclose = abs_err <= tol.abs + tol.rel * e.abs();
        assert!(
            allclose,
            "{what}: allclose failed at {i}: got={g:e} expected={e:e} \
             abs_err={abs_err:e} (atol={:e}, rtol={:e})",
            tol.abs, tol.rel
        );
    }
}

/// Read a fixture's float-valued label array as `i64` (load_npz decodes only
/// 4/8-byte float arrays, so labels are stored float-valued — kmeans_test.rs:133).
fn labels_i64(case: &OracleCase, name: &str) -> Vec<i64> {
    case.expect_f64(name).iter().map(|&v| v as i64).collect()
}

/// The f64 capability gate (verbatim from kmeans_test.rs:183-189): cpu runs f64,
/// rocm skips-with-log per the CubeCL-HIP F64 gap. Returns `true` when the caller
/// should early-return.
fn skip_f64(test: &str) -> bool {
    let backend = capability::active_backend_name();
    capability::log_oracle_dtype(capability::FloatKind::F64, backend, "default");
    if capability::skip_f64_with_log() {
        println!("hdbscan {test} f64 backend={backend}: SKIPPED (no f64 support on this adapter)");
        return true;
    }
    false
}

// ---------------------------------------------------------------------------
// HDBS-02 / D-03: labels match sklearn exactly up to a -1-pinned permutation,
// per metric × {f32, f64}. The exact-label gate uses the PINNED-NOISE matcher so
// a noise/cluster mismatch is a genuine failure (never permuted away).
//
// WAVE-0: the shell `Metric` has only `Euclidean` and `fit` is trivial, so the
// real fit-vs-oracle comparison cannot run yet. Each gate loads its fixture and
// invokes `best_match_accuracy_pinned_noise` on the oracle's own
// sklearn-vs-hdbscan label pair as a self-consistency placeholder that exercises
// the exact matcher this gate will use. Un-ignore + swap to the fitted labels in
// 15-NN.
// ---------------------------------------------------------------------------

/// Shared body: load `hdbscan_{metric}_{dtype}.npz`, assert the fitted labels are
/// a -1-pinned permutation of sklearn's. In Wave 0 the "fitted" labels are stubbed
/// from the oracle cross-check (sklearn vs hdbscan) so the matcher + fixture wiring
/// is exercised; 15-NN replaces `got` with `Hdbscan::fit(...).labels()`.
fn run_labels_match(case: &OracleCase, label: &str) {
    let sklearn = labels_i64(case, "labels");
    // 15-NN: replace `got` with the fitted mlrs labels.
    let got = sklearn.clone();
    let acc = best_match_accuracy_pinned_noise(&got, &sklearn);
    assert!(
        (acc - 1.0).abs() < f64::EPSILON,
        "{label}: labels not a -1-pinned permutation of sklearn (acc={acc})"
    );
}

macro_rules! labels_match_metric {
    ($f32_name:ident, $f64_name:ident, $metric:literal) => {
        #[test]
        #[ignore = "un-ignore in 15-NN: needs the back-end fit + extended Metric"]
        fn $f32_name() {
            let backend = capability::active_backend_name();
            capability::log_oracle_dtype(capability::FloatKind::F32, backend, "default");
            let case = load_npz(fixture(concat!("hdbscan_", $metric, "_f32_seed42.npz")))
                .expect(concat!("load hdbscan_", $metric, "_f32"));
            run_labels_match(&case, concat!("labels_match_sklearn ", $metric, " f32"));
        }

        #[test]
        #[ignore = "un-ignore in 15-NN: needs the back-end fit + extended Metric"]
        fn $f64_name() {
            if skip_f64(concat!("labels_match_sklearn ", $metric)) {
                return;
            }
            let case = load_npz(fixture(concat!("hdbscan_", $metric, "_f64_seed42.npz")))
                .expect(concat!("load hdbscan_", $metric, "_f64"));
            run_labels_match(&case, concat!("labels_match_sklearn ", $metric, " f64"));
        }
    };
}

// A single `labels_match_sklearn` driver per metric × dtype (HDBS-02). The
// function name `labels_match_sklearn_*` keeps the VALIDATION targeted-run command
// `cargo test ... labels_match_sklearn` selecting the whole family.
labels_match_metric!(
    labels_match_sklearn_euclidean_f32,
    labels_match_sklearn_euclidean_f64,
    "euclidean"
);
labels_match_metric!(
    labels_match_sklearn_manhattan_f32,
    labels_match_sklearn_manhattan_f64,
    "manhattan"
);
labels_match_metric!(
    labels_match_sklearn_cosine_f32,
    labels_match_sklearn_cosine_f64,
    "cosine"
);
labels_match_metric!(
    labels_match_sklearn_chebyshev_f32,
    labels_match_sklearn_chebyshev_f64,
    "chebyshev"
);
labels_match_metric!(
    labels_match_sklearn_minkowski_f32,
    labels_match_sklearn_minkowski_f64,
    "minkowski"
);
labels_match_metric!(
    labels_match_sklearn_precomputed_f32,
    labels_match_sklearn_precomputed_f64,
    "precomputed"
);

// ---------------------------------------------------------------------------
// HDBS-02 / D-04 TRUE GATE: the tie-heavy + duplicate-point fixture. Same
// pinned-noise exactness gate over an adversarial tie-heavy MST design, PLUS the
// duplicate row (R-9) must carry its partner's label.
// ---------------------------------------------------------------------------

/// `tie_break_exact` f32 — the D-04 TRUE GATE on the tie-heavy lattice + duplicate.
#[test]
#[ignore = "un-ignore in 15-NN: needs the back-end fit (tie-heavy MST handling)"]
fn tie_break_exact_f32() {
    let backend = capability::active_backend_name();
    capability::log_oracle_dtype(capability::FloatKind::F32, backend, "default");
    let case = load_npz(fixture("hdbscan_tieheavy_f32_seed42.npz")).expect("load tieheavy f32");
    run_tie_break(&case, "tie_break_exact f32");
}

/// `tie_break_exact` f64 — the D-04 TRUE GATE (cpu runs; rocm skips-with-log).
#[test]
#[ignore = "un-ignore in 15-NN: needs the back-end fit (tie-heavy MST handling)"]
fn tie_break_exact_f64() {
    if skip_f64("tie_break_exact") {
        return;
    }
    let case = load_npz(fixture("hdbscan_tieheavy_f64_seed42.npz")).expect("load tieheavy f64");
    run_tie_break(&case, "tie_break_exact f64");
}

fn run_tie_break(case: &OracleCase, label: &str) {
    let sklearn = labels_i64(case, "labels");
    // 15-NN: replace `got` with the fitted mlrs labels on the tie-heavy fixture.
    let got = sklearn.clone();
    let acc = best_match_accuracy_pinned_noise(&got, &sklearn);
    assert!(
        (acc - 1.0).abs() < f64::EPSILON,
        "{label}: tie-heavy labels not a -1-pinned permutation of sklearn (acc={acc})"
    );

    // R-9: the duplicate row must share its partner's label (a genuine distance-0
    // duplicate, identical to the oracle).
    let dup_a = case.expect_f64("dup_row_a")[0] as usize;
    let dup_b = case.expect_f64("dup_row_b")[0] as usize;
    assert_eq!(
        got[dup_a], got[dup_b],
        "{label}: duplicate rows {dup_a}/{dup_b} must share a label (R-9)"
    );
}

// ---------------------------------------------------------------------------
// HDBS-01 / D-06: per-point `probabilities_` match sklearn ≤1e-5.
// ---------------------------------------------------------------------------

/// `probabilities_match` f32 — per-point membership strength vs sklearn ≤1e-5.
#[test]
#[ignore = "un-ignore in 15-NN: needs the back-end fit + probabilities accessor"]
fn probabilities_match_f32() {
    let backend = capability::active_backend_name();
    capability::log_oracle_dtype(capability::FloatKind::F32, backend, "default");
    let case = load_npz(fixture("hdbscan_euclidean_f32_seed42.npz")).expect("load euclidean f32");
    run_probabilities(&case, &F32_TOL, "probabilities_match f32");
}

/// `probabilities_match` f64 — per-point membership strength (cpu; rocm skips).
#[test]
#[ignore = "un-ignore in 15-NN: needs the back-end fit + probabilities accessor"]
fn probabilities_match_f64() {
    if skip_f64("probabilities_match") {
        return;
    }
    let case = load_npz(fixture("hdbscan_euclidean_f64_seed42.npz")).expect("load euclidean f64");
    run_probabilities(&case, &F64_TOL, "probabilities_match f64");
}

fn run_probabilities(case: &OracleCase, tol: &Tolerance, label: &str) {
    let probabilities = case.expect_f64("probabilities").to_vec();
    // 15-NN: replace `got` with the fitted mlrs `probabilities_`.
    let got = probabilities.clone();
    assert_close(&got, &probabilities, tol, label);
}

// ---------------------------------------------------------------------------
// HDBS-03 / D-07: GLOSH `outlier_scores_` match hdbscan 0.8.44 ≤1e-5.
// ---------------------------------------------------------------------------

/// `outlier_scores_match` f32 — GLOSH per-point scores vs hdbscan 0.8.44 ≤1e-5.
#[test]
#[ignore = "un-ignore in 15-NN: needs the back-end fit + outlier_scores accessor"]
fn outlier_scores_match_f32() {
    let backend = capability::active_backend_name();
    capability::log_oracle_dtype(capability::FloatKind::F32, backend, "default");
    let case = load_npz(fixture("hdbscan_euclidean_f32_seed42.npz")).expect("load euclidean f32");
    run_outlier_scores(&case, &F32_TOL, "outlier_scores_match f32");
}

/// `outlier_scores_match` f64 — GLOSH per-point scores (cpu; rocm skips).
#[test]
#[ignore = "un-ignore in 15-NN: needs the back-end fit + outlier_scores accessor"]
fn outlier_scores_match_f64() {
    if skip_f64("outlier_scores_match") {
        return;
    }
    let case = load_npz(fixture("hdbscan_euclidean_f64_seed42.npz")).expect("load euclidean f64");
    run_outlier_scores(&case, &F64_TOL, "outlier_scores_match f64");
}

fn run_outlier_scores(case: &OracleCase, tol: &Tolerance, label: &str) {
    let outlier_scores = case.expect_f64("outlier_scores").to_vec();
    // 15-NN: replace `got` with the fitted mlrs GLOSH `outlier_scores_`.
    let got = outlier_scores.clone();
    assert_close(&got, &outlier_scores, tol, label);
}

// ---------------------------------------------------------------------------
// HDBS-04 / Pitfall 6: `centroids_`/`medoids_` match sklearn ≤1e-5 under the SAME
// label permutation (map each fitted cluster id to its sklearn id via the label
// confusion, then compare the centre rows).
// ---------------------------------------------------------------------------

/// `centers_match` f32 — `centroids_`/`medoids_` vs sklearn (same permutation).
#[test]
#[ignore = "un-ignore in 15-NN: needs the back-end fit + store_centers accessors"]
fn centers_match_f32() {
    let backend = capability::active_backend_name();
    capability::log_oracle_dtype(capability::FloatKind::F32, backend, "default");
    let case = load_npz(fixture("hdbscan_euclidean_f32_seed42.npz")).expect("load euclidean f32");
    run_centers(&case, &F32_TOL, "centers_match f32");
}

/// `centers_match` f64 — `centroids_`/`medoids_` vs sklearn (cpu; rocm skips).
#[test]
#[ignore = "un-ignore in 15-NN: needs the back-end fit + store_centers accessors"]
fn centers_match_f64() {
    if skip_f64("centers_match") {
        return;
    }
    let case = load_npz(fixture("hdbscan_euclidean_f64_seed42.npz")).expect("load euclidean f64");
    run_centers(&case, &F64_TOL, "centers_match f64");
}

fn run_centers(case: &OracleCase, tol: &Tolerance, label: &str) {
    let sklearn = labels_i64(case, "labels");
    let centroids_ref = case.expect_f64("centroids");
    let medoids_ref = case.expect_f64("medoids");
    let n_features = 4usize; // euclidean fixture geometry (HDB_BLOB_N_FEATURES).
    let n_clusters = centroids_ref.len() / n_features;

    // 15-NN: replace `got_labels`/`got_centroids`/`got_medoids` with the fitted
    // mlrs labels + `centroids_`/`medoids_`. The Wave-0 placeholder maps the oracle
    // onto itself (identity permutation) so the `best_mapping` + per-cluster
    // `assert_close` plumbing (Pitfall 6) is exercised.
    let got_labels = sklearn.clone();
    let got_centroids = centroids_ref.to_vec();
    let got_medoids = medoids_ref.to_vec();

    let mapping = best_mapping(&got_labels, &sklearn);
    for fitted_c in 0..n_clusters {
        let ref_c = *mapping
            .get(&(fitted_c as i64))
            .unwrap_or_else(|| panic!("{label}: cluster {fitted_c} unmapped"))
            as usize;
        let cg = &got_centroids[fitted_c * n_features..(fitted_c + 1) * n_features];
        let ce = &centroids_ref[ref_c * n_features..(ref_c + 1) * n_features];
        assert_close(
            cg,
            ce,
            tol,
            &format!("{label} centroid[{fitted_c}->{ref_c}]"),
        );
        let mg = &got_medoids[fitted_c * n_features..(fitted_c + 1) * n_features];
        let me = &medoids_ref[ref_c * n_features..(ref_c + 1) * n_features];
        assert_close(mg, me, tol, &format!("{label} medoid[{fitted_c}->{ref_c}]"));
    }
}

// ---------------------------------------------------------------------------
// HDBS-01 / D-09: the nested-density fixture's non-default eom/leaf/epsilon/
// max_cluster_size/alpha label vectors are each an exact pinned-noise permutation
// of the corresponding oracle. (Epsilon is cross-oracled against hdbscan 0.8.44 —
// sklearn 1.9.0's epsilon_search crashes on merging trees; see gen_oracle.py.)
// ---------------------------------------------------------------------------

/// `selection_knobs` f32 — each non-default knob's labels match its oracle.
#[test]
#[ignore = "un-ignore in 15-NN: needs the back-end fit + selection knobs"]
fn selection_knobs_f32() {
    let backend = capability::active_backend_name();
    capability::log_oracle_dtype(capability::FloatKind::F32, backend, "default");
    let case = load_npz(fixture("hdbscan_nested_f32_seed42.npz")).expect("load nested f32");
    run_selection_knobs(&case, "selection_knobs f32");
}

/// `selection_knobs` f64 — each non-default knob's labels (cpu; rocm skips).
#[test]
#[ignore = "un-ignore in 15-NN: needs the back-end fit + selection knobs"]
fn selection_knobs_f64() {
    if skip_f64("selection_knobs") {
        return;
    }
    let case = load_npz(fixture("hdbscan_nested_f64_seed42.npz")).expect("load nested f64");
    run_selection_knobs(&case, "selection_knobs f64");
}

fn run_selection_knobs(case: &OracleCase, label: &str) {
    // Each non-default-knob oracle label vector. 15-NN: fit `Hdbscan` with each
    // knob and replace the `got_*` clone with the fitted labels.
    for knob in [
        "labels_eom",
        "labels_leaf",
        "labels_maxcluster",
        "labels_alpha",
        "labels_epsilon",
    ] {
        let oracle = labels_i64(case, knob);
        let got = oracle.clone();
        let acc = best_match_accuracy_pinned_noise(&got, &oracle);
        assert!(
            (acc - 1.0).abs() < f64::EPSILON,
            "{label} [{knob}]: labels not a -1-pinned permutation of the oracle (acc={acc})"
        );
    }
}

// ---------------------------------------------------------------------------
// HDBS-01 / D-08: data-independent build validation — bad hyperparameters are
// rejected at `build()` with a typed `BuildError`, BEFORE any data is seen.
// (Extends the kept Phase-12 `build_rejects_bad_min_cluster_size`.) This gate
// RUNS now — the build path already exists on the shell.
// ---------------------------------------------------------------------------

/// BLDR-01: `Hdbscan::new()` equals `Hdbscan::builder().build()?` on the
/// hyperparameter subset (single-source defaults). Pure host comparison. KEPT
/// verbatim from the Phase-12 shell.
#[test]
fn defaults_equal() {
    let from_new = Hdbscan::<f64>::new();
    let from_builder = Hdbscan::<f64>::builder()
        .build::<f64>()
        .expect("default HdbscanBuilder builds");
    assert!(
        from_new.hyperparams_eq(&from_builder),
        "Hdbscan::new() and builder().build()? must agree on hyperparameters (BLDR-01)"
    );
}

/// D-08 build validation (HDBS-01): a `min_cluster_size < 2` is rejected at
/// `build()` with the typed `BuildError::InvalidMinClusterSize`, BEFORE any data.
/// (Extends the Phase-12 `build_rejects_bad_min_cluster_size`; 15-NN adds the
/// `min_samples`/`max_cluster_size`/`alpha`/minkowski-`p` cases as those typed
/// `BuildError` variants land.)
#[test]
fn build_validation() {
    let bad = Hdbscan::<f64>::builder()
        .min_cluster_size(1)
        .build::<f64>()
        .err();
    assert!(
        matches!(
            bad,
            Some(BuildError::InvalidMinClusterSize { min_cluster_size, .. })
                if min_cluster_size == 1
        ),
        "min_cluster_size < 2 must be BuildError::InvalidMinClusterSize, got {bad:?}"
    );

    // min_samples = Some(0) is rejected; Some(1) is accepted (15-03 / D-09).
    let bad_ms = Hdbscan::<f64>::builder()
        .min_samples(Some(0))
        .build::<f64>()
        .err();
    assert!(
        matches!(
            bad_ms,
            Some(BuildError::InvalidMinSamples { min_samples, .. }) if min_samples == 0
        ),
        "min_samples = Some(0) must be BuildError::InvalidMinSamples, got {bad_ms:?}"
    );
    assert!(
        Hdbscan::<f64>::builder()
            .min_samples(Some(1))
            .build::<f64>()
            .is_ok(),
        "min_samples = Some(1) must be accepted"
    );

    // max_cluster_size = 3 with min_cluster_size = 5 is rejected (neither 0 nor
    // >= mcs); 0 (unbounded) and 5 (== mcs) are accepted.
    let bad_mxc = Hdbscan::<f64>::builder()
        .min_cluster_size(5)
        .max_cluster_size(3)
        .build::<f64>()
        .err();
    assert!(
        matches!(
            bad_mxc,
            Some(BuildError::InvalidMaxClusterSize { max_cluster_size, min_cluster_size, .. })
                if max_cluster_size == 3 && min_cluster_size == 5
        ),
        "max_cluster_size below min_cluster_size must be InvalidMaxClusterSize, got {bad_mxc:?}"
    );
    assert!(
        Hdbscan::<f64>::builder()
            .min_cluster_size(5)
            .max_cluster_size(0)
            .build::<f64>()
            .is_ok(),
        "max_cluster_size = 0 (unbounded) must be accepted"
    );
    assert!(
        Hdbscan::<f64>::builder()
            .min_cluster_size(5)
            .max_cluster_size(5)
            .build::<f64>()
            .is_ok(),
        "max_cluster_size == min_cluster_size must be accepted"
    );

    // alpha <= 0 is rejected; alpha = 1.0 is accepted.
    let bad_alpha = Hdbscan::<f64>::builder().alpha(0.0).build::<f64>().err();
    assert!(
        matches!(
            bad_alpha,
            Some(BuildError::InvalidAlphaHdbscan { alpha, .. }) if alpha == 0.0
        ),
        "alpha = 0.0 must be BuildError::InvalidAlphaHdbscan, got {bad_alpha:?}"
    );
    assert!(
        Hdbscan::<f64>::builder().alpha(-1.0).build::<f64>().is_err(),
        "negative alpha must be rejected"
    );
    assert!(
        Hdbscan::<f64>::builder().alpha(1.0).build::<f64>().is_ok(),
        "alpha = 1.0 must be accepted"
    );

    // Metric::Minkowski { p < 1 } is rejected; p = 2.0 accepted; Precomputed
    // round-trips through the builder.
    let bad_p = Hdbscan::<f64>::builder()
        .metric(Metric::Minkowski { p: 0.5 })
        .build::<f64>()
        .err();
    assert!(
        matches!(
            bad_p,
            Some(BuildError::InvalidMinkowskiP { p, .. }) if p == 0.5
        ),
        "minkowski p < 1 must be BuildError::InvalidMinkowskiP, got {bad_p:?}"
    );
    assert!(
        Hdbscan::<f64>::builder()
            .metric(Metric::Minkowski { p: 2.0 })
            .build::<f64>()
            .is_ok(),
        "minkowski p = 2.0 must be accepted"
    );
    assert!(
        Hdbscan::<f64>::builder()
            .metric(Metric::Precomputed)
            .build::<f64>()
            .is_ok(),
        "Metric::Precomputed must construct"
    );
}

// ---------------------------------------------------------------------------
// HDBS-01 / T-15-OVF: the device front-end must not leak across re-fits, and must
// keep `peak_bytes` sub-quadratic (no full `n×n` resident — query-axis-tiled).
//
// WAVE-0: the shell `fit` is trivial; the re-fit-no-growth idiom (from the kept
// Phase-12 `fit_no_leak`) runs now over Euclidean default. The sub-quadratic
// `peak_bytes` assertion is added in 15-NN once the device front-end exists.
// ---------------------------------------------------------------------------

/// `memory_gate` — re-CONSTRUCT + re-fit at the same shape does not grow
/// `live_bytes` (the consuming `fit(self)` forces reconstruction each iteration).
/// The kept Phase-12 PoolStats idiom; 15-NN adds the sub-quadratic `peak_bytes`
/// gate once the n×n device front-end exists.
#[test]
fn memory_gate() {
    use mlrs_algos::typestate::Fit;
    use mlrs_backend::device_array::DeviceArray;
    use mlrs_backend::pool::BufferPool;
    use mlrs_backend::runtime::{self, ActiveRuntime};

    if skip_f64("memory_gate") {
        return;
    }

    let client = runtime::active_client();
    let mut pool: BufferPool<ActiveRuntime> = BufferPool::new(client);

    let n = 9usize;
    let p = 4usize;
    let x_host: Vec<f64> = (0..n * p).map(|i| i as f64).collect();
    let x_dev: DeviceArray<ActiveRuntime, f64> = DeviceArray::from_host(&mut pool, &x_host);

    let fitted = Hdbscan::<f64>::new()
        .fit(&mut pool, &x_dev, None, (n, p))
        .expect("first fit");
    drop(fitted);
    let live_after_first = pool.stats().live_bytes;

    const REFITS: usize = 4;
    for k in 0..REFITS {
        let fitted = Hdbscan::<f64>::new()
            .fit(&mut pool, &x_dev, None, (n, p))
            .expect("re-fit");
        drop(fitted);
        let live = pool.stats().live_bytes;
        assert!(
            live <= live_after_first,
            "live_bytes grew across re-construct+fit {k}: {live} > first {live_after_first}"
        );
    }
}

// ---------------------------------------------------------------------------
// HDBS-01: edge cases — all-noise / single-cluster / n<min_cluster_size match
// sklearn. Pinned-noise exact gate over the degenerate fixtures.
// ---------------------------------------------------------------------------

/// `edge_cases` f32 — all-noise / single-cluster / tiny fixtures match sklearn.
#[test]
#[ignore = "un-ignore in 15-NN: needs the back-end fit"]
fn edge_cases_f32() {
    let backend = capability::active_backend_name();
    capability::log_oracle_dtype(capability::FloatKind::F32, backend, "default");
    run_edge_cases("f32", "edge_cases f32");
}

/// `edge_cases` f64 — degenerate fixtures match sklearn (cpu; rocm skips).
#[test]
#[ignore = "un-ignore in 15-NN: needs the back-end fit"]
fn edge_cases_f64() {
    if skip_f64("edge_cases") {
        return;
    }
    run_edge_cases("f64", "edge_cases f64");
}

fn run_edge_cases(dtype_tag: &str, label: &str) {
    for structure in ["allnoise", "single", "tiny"] {
        let name = format!("hdbscan_{structure}_{dtype_tag}_seed42.npz");
        let case = load_npz(fixture(&name)).unwrap_or_else(|e| panic!("load {name}: {e}"));
        let sklearn = labels_i64(&case, "labels");
        // 15-NN: replace `got` with the fitted mlrs labels on each edge fixture.
        let got = sklearn.clone();
        let acc = best_match_accuracy_pinned_noise(&got, &sklearn);
        assert!(
            (acc - 1.0).abs() < f64::EPSILON,
            "{label} [{structure}]: labels not a -1-pinned permutation of sklearn (acc={acc})"
        );
    }
}

// ---------------------------------------------------------------------------
// HDBS-02 / plan 15-03: the MST + single-linkage host back-end. The full
// fit-vs-oracle label gate runs in 15-04 (condense/select) + 15-05 (device
// front-end); here we characterize the two oracle Prim variants + the UnionFind
// single-linkage DIRECTLY on hand-built DISTINCT-weight inputs (RESEARCH
// Pitfall 1 option 2 — distinct weights make the sort tie-free and the hierarchy
// deterministic). These assert VALUES (not just non-panic), per R-9.
// ---------------------------------------------------------------------------

use mlrs_algos::cluster::hdbscan::mst::{
    argsort_by_weight, core_distances_dense, mst_from_data_matrix, mst_from_mutual_reachability,
    mutual_reachability_dense,
};
use mlrs_algos::cluster::hdbscan::single_linkage::{make_single_linkage, UnionFind};

/// Variant A (`mst_from_mutual_reachability`) recovers the expected spanning tree
/// on a small dense path-graph distance matrix with DISTINCT weights, and the
/// FIRST-min `argmin` tie-break is exercised. 4-point path 0-1-2-3 with edge
/// weights 1, 2, 3 along the path and larger off-path distances → the MST is the
/// path itself.
#[test]
fn mst_variant_a_distinct_weights() {
    let n = 4;
    // Symmetric distance matrix: path 0-1 (1.0), 1-2 (2.0), 2-3 (3.0); off-path
    // distances strictly larger so the unique MST is the path.
    let d = vec![
        0.0, 1.0, 5.0, 9.0, //
        1.0, 0.0, 2.0, 6.0, //
        5.0, 2.0, 0.0, 3.0, //
        9.0, 6.0, 3.0, 0.0, //
    ];
    // min_samples=1 → core distance = 0th smallest = the self-zero, so MR == d.
    let core = core_distances_dense(&d, n, 1);
    assert_eq!(core, vec![0.0, 0.0, 0.0, 0.0], "core dist with ms=1 is the self-zero");
    let mr = mutual_reachability_dense(&d, &core, n);
    assert_eq!(mr, d, "MR with zero core distances equals the distance matrix");

    let mst = mst_from_mutual_reachability(&mr, n);
    assert_eq!(mst.len(), n - 1, "an MST over n points has n-1 edges");
    // Edge set (unordered endpoints) must be {0-1, 1-2, 2-3} with weights 1,2,3.
    let mut weights: Vec<f64> = mst.iter().map(|&(_, _, w)| w).collect();
    weights.sort_by(|a, b| a.total_cmp(b));
    assert_eq!(weights, vec![1.0, 2.0, 3.0], "MST weights are the path edges");
}

/// Variant B (`mst_from_data_matrix`) on the SAME path graph via a closure that
/// returns the raw pairwise distance: with `alpha=1.0` and zero core distances it
/// recovers the identical path MST, and the strict-`<` lowest-`j` tie logic is
/// exercised (no panic, deterministic).
#[test]
fn mst_variant_b_matches_path() {
    let n = 4;
    let d = vec![
        0.0, 1.0, 5.0, 9.0, //
        1.0, 0.0, 2.0, 6.0, //
        5.0, 2.0, 0.0, 3.0, //
        9.0, 6.0, 3.0, 0.0, //
    ];
    let core = vec![0.0; n]; // raw core distances (Variant-B placement)
    let mst = mst_from_data_matrix(&core, n, 1.0, |i, j| d[i * n + j]);
    assert_eq!(mst.len(), n - 1);
    let mut weights: Vec<f64> = mst.iter().map(|&(_, _, w)| w).collect();
    weights.sort_by(|a, b| a.total_cmp(b));
    assert_eq!(weights, vec![1.0, 2.0, 3.0], "Variant B recovers the path MST");
}

/// The Variant-B alpha placement divides the PAIRWISE distance (not the core) by
/// alpha: with alpha=2 and zero core, every MST weight halves.
#[test]
fn mst_variant_b_alpha_divides_pairwise() {
    let n = 3;
    let d = vec![
        0.0, 2.0, 8.0, //
        2.0, 0.0, 4.0, //
        8.0, 4.0, 0.0, //
    ];
    let core = vec![0.0; n];
    let mst = mst_from_data_matrix(&core, n, 2.0, |i, j| d[i * n + j]);
    let mut weights: Vec<f64> = mst.iter().map(|&(_, _, w)| w).collect();
    weights.sort_by(|a, b| a.total_cmp(b));
    // raw path edges 2 and 4, divided by alpha=2 → 1 and 2.
    assert_eq!(weights, vec![1.0, 2.0], "alpha divides the pairwise distance (Variant B)");
}

/// `make_single_linkage` relabels `N+i` per merge and accumulates sizes. On the
/// distinct-weight path MST the hierarchy is deterministic: 3 merges, sizes
/// 2,3,4, fresh labels 4,5,6.
#[test]
fn single_linkage_relabels_and_accumulates() {
    let n = 4;
    // Argsorted path MST: (0,1,1), (1,2,2), (2,3,3).
    let edges = vec![(0usize, 1usize, 1.0f64), (1, 2, 2.0), (2, 3, 3.0)];
    let sorted = argsort_by_weight(&edges);
    assert_eq!(sorted, edges, "distinct ascending weights are already sorted");

    let sl = make_single_linkage(&sorted, n);
    assert_eq!(sl.len(), n - 1);
    // First merge: find(0)=0, find(1)=1 → new label 4, size 2.
    assert_eq!((sl[0].left, sl[0].right, sl[0].size), (0, 1, 2));
    assert_eq!(sl[0].distance, 1.0);
    // Second merge: find(1)=4 (compressed), find(2)=2 → label 5, size 3.
    assert_eq!((sl[1].left, sl[1].right, sl[1].size), (4, 2, 3));
    // Third merge: find(2)=5, find(3)=3 → label 6, size 4.
    assert_eq!((sl[2].left, sl[2].right, sl[2].size), (5, 3, 4));
}

/// The UnionFind `fast_find` path-compresses and `union` mints fresh labels —
/// the load-bearing single-linkage invariant.
#[test]
fn union_find_fresh_labels() {
    let mut uf = UnionFind::new(3); // labels 0,1,2 singletons; internal 3,4
    assert_eq!(uf.fast_find(0), 0);
    uf.union(0, 1); // mint label 3, size 2
    assert_eq!(uf.size_of(3), 2);
    assert_eq!(uf.fast_find(0), 3, "0 now roots at fresh label 3");
    assert_eq!(uf.fast_find(1), 3);
    uf.union(3, 2); // mint label 4, size 3
    assert_eq!(uf.size_of(4), 3);
    assert_eq!(uf.fast_find(2), 4);
    assert_eq!(uf.fast_find(0), 4, "path-compressed to the new root 4");
}

/// The precomputed `fit` path runs the full host MST → single-linkage pipeline
/// and stores the hierarchy on the estimator (plan 15-03). Validates squareness
/// rejection AND that a valid square matrix yields an `n-1`-edge hierarchy.
#[test]
fn precomputed_fit_builds_single_linkage() {
    use mlrs_algos::cluster::hdbscan::Metric;
    use mlrs_algos::typestate::Fit;
    use mlrs_backend::device_array::DeviceArray;
    use mlrs_backend::pool::BufferPool;
    use mlrs_backend::runtime::{self, ActiveRuntime};

    if skip_f64("precomputed_fit") {
        return;
    }

    let client = runtime::active_client();
    let mut pool: BufferPool<ActiveRuntime> = BufferPool::new(client);

    let n = 4usize;
    // A symmetric square distance matrix (path graph, distinct weights).
    let d: Vec<f64> = vec![
        0.0, 1.0, 5.0, 9.0, //
        1.0, 0.0, 2.0, 6.0, //
        5.0, 2.0, 0.0, 3.0, //
        9.0, 6.0, 3.0, 0.0, //
    ];
    let x_dev: DeviceArray<ActiveRuntime, f64> = DeviceArray::from_host(&mut pool, &d);

    let fitted = Hdbscan::<f64>::builder()
        .min_cluster_size(2)
        .metric(Metric::Precomputed)
        .build::<f64>()
        .expect("build precomputed")
        .fit(&mut pool, &x_dev, None, (n, n))
        .expect("precomputed fit");

    let sl = fitted
        .single_linkage()
        .expect("precomputed fit stores the single-linkage hierarchy");
    assert_eq!(sl.len(), n - 1, "hierarchy has n-1 merge rows");
    // The top merge spans all 4 points.
    assert_eq!(sl[n - 2].size, n, "final merge unites all points");

    // Squareness rejection (T-15-03-V5a): a non-square (n, p!=n) shape errors
    // before any host read.
    let bad = Hdbscan::<f64>::builder()
        .min_cluster_size(2)
        .metric(Metric::Precomputed)
        .build::<f64>()
        .expect("build")
        .fit(&mut pool, &x_dev, None, (2, 8));
    assert!(bad.is_err(), "non-square precomputed matrix must be rejected");
}
